### PR TITLE
Bugfix collection and default value removal

### LINKED ISSUE #327: VerletListsCells produce wrong results
**Describe the bug**
Results using VerletListsCells are wrong.

**To Reproduce**
1. Use Argon example with 
```Xml
<datastructure type="AutoPas">
  <allowedTraversals>c01, c08, c18, sli, v01, v18, var, verlet-sliced, verlet-lists, c01-combined-SoA</allowedTraversals>
  <allowedContainers>linkedCells, verletLists, varVerletListsAsBuild, verletListsCells</allowedContainers>
  <allowedContainers>linkedCells, verletLists, varVerletListsAsBuild</allowedContainers>
  <selectorStrategy>fastestMedian</selectorStrategy>
  <dataLayouts>AoS, SoA</dataLayouts>
  <newton3>enabled, disabled</newton3>
  <tuningInterval>10000</tuningInterval>
  <tuningSamples>10</tuningSamples>
  <rebuildFrequency>10</rebuildFrequency>
  <skin>1.</skin><!--roughly 10% of cutoff-->
</datastructure>
<cutoffs type="CenterOfMass">
  <radiusLJ unit="reduced">16.0702</radiusLJ>
</cutoffs>
```
2. Results jump around:
```
[2019-08-05 15:35:46.555] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153546 0.466178 [0]	Simstep = 0	T = 2.53016e-05	U_pot = -2.09941	p = -2.67655e-07
[2019-08-05 15:35:47.036] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153547 0.598477 [0]	Simstep = 1	T = 2.53835e-05	U_pot = -2.09966	p = -2.68526e-07
[2019-08-05 15:35:47.168] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153547 0.730181 [0]	Simstep = 2	T = 0.000333466	U_pot = -2.10156	p = 2.18636e-07
[2019-08-05 15:35:47.299] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153547 0.860283 [0]	Simstep = 3	T = 0.000557967	U_pot = -2.10423	p = 5.68495e-07
[2019-08-05 15:35:47.435] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153547 1.00533  [0]	Simstep = 4	T = 0.000618424	U_pot = -2.10702	p = 6.54283e-07
[2019-08-05 15:35:47.576] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153547 1.13854  [0]	Simstep = 5	T = 0.000631257	U_pot = -2.10981	p = 6.63559e-07
[2019-08-05 15:35:47.709] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153547 1.27811  [0]	Simstep = 6	T = 0.000633835	U_pot = -2.11253	p = 6.56578e-07
[2019-08-05 15:35:47.848] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153547 1.41459  [0]	Simstep = 7	T = 0.00063433	U_pot = -2.11516	p = 6.46506e-07
[2019-08-05 15:35:47.989] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153548 1.56299  [0]	Simstep = 8	T = 0.000634406	U_pot = -2.1177	p = 6.36066e-07
[2019-08-05 15:35:48.135] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153548 1.70189  [0]	Simstep = 9	T = 0.000634395	U_pot = -2.12027	p = 6.25586e-07
[2019-08-05 15:35:48.241] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 1.77174  [0]	Simstep = 10	T = 0.000634365	U_pot = -2.12266	p = 6.15521e-07
[2019-08-05 15:35:48.342] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 1.8728   [0]	Simstep = 11	T = 0.000634331	U_pot = -2.12495	p = 6.0581e-07
[2019-08-05 15:35:48.441] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 1.97181  [0]	Simstep = 12	T = 0.000634294	U_pot = -2.1273	p = 5.96182e-07
[2019-08-05 15:35:48.542] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 2.0742   [0]	Simstep = 13	T = 0.000634257	U_pot = -2.12951	p = 5.86996e-07
[2019-08-05 15:35:48.643] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 2.17427  [0]	Simstep = 14	T = 0.000634218	U_pot = -2.13161	p = 5.78181e-07
[2019-08-05 15:35:48.742] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 2.27254  [0]	Simstep = 15	T = 0.000634178	U_pot = -2.1336	p = 5.69753e-07
[2019-08-05 15:35:48.841] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 2.37073  [0]	Simstep = 16	T = 0.000634138	U_pot = -2.13556	p = 5.61599e-07
[2019-08-05 15:35:48.940] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153548 2.46993  [0]	Simstep = 17	T = 0.000634098	U_pot = -2.13743	p = 5.5381e-07
[2019-08-05 15:35:49.038] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153549 2.56741  [0]	Simstep = 18	T = 0.000634057	U_pot = -2.13903	p = 5.4666e-07
[2019-08-05 15:35:49.135] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153549 2.66638  [0]	Simstep = 19	T = 0.000634017	U_pot = -2.1407	p = 5.3966e-07
[2019-08-05 15:35:49.205] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 2.71309  [0]	Simstep = 20	T = 0.000633975	U_pot = -2.14212	p = 5.33272e-07
[2019-08-05 15:35:49.283] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 2.78687  [0]	Simstep = 21	T = 0.000633934	U_pot = -2.14344	p = 5.27303e-07
[2019-08-05 15:35:49.356] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 2.86133  [0]	Simstep = 22	T = 0.000633893	U_pot = -2.14472	p = 5.21615e-07
[2019-08-05 15:35:49.430] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 2.93427  [0]	Simstep = 23	T = 0.000633851	U_pot = -2.14598	p = 5.16222e-07
[2019-08-05 15:35:49.503] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 3.00805  [0]	Simstep = 24	T = 0.00063381	U_pot = -2.14715	p = 5.11218e-07
[2019-08-05 15:35:49.577] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 3.08177  [0]	Simstep = 25	T = 0.000633768	U_pot = -2.14807	p = 5.06848e-07
[2019-08-05 15:35:49.650] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 3.15364  [0]	Simstep = 26	T = 0.000633727	U_pot = -2.14887	p = 5.02906e-07
[2019-08-05 15:35:49.722] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 3.22641  [0]	Simstep = 27	T = 0.000633685	U_pot = -2.14959	p = 4.99356e-07
[2019-08-05 15:35:49.794] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 3.29914  [0]	Simstep = 28	T = 0.000633644	U_pot = -2.15023	p = 4.96187e-07
[2019-08-05 15:35:49.868] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
INFO:	20190805T153549 3.37172  [0]	Simstep = 29	T = 0.000633603	U_pot = -2.15078	p = 4.93396e-07
[2019-08-05 15:35:49.912] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153549 3.40486  [0]	Simstep = 30	T = 0.000633563	U_pot = -2.15119	p = 4.91083e-07
[2019-08-05 15:35:49.973] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153549 3.46707  [0]	Simstep = 31	T = 0.000633523	U_pot = -2.15158	p = 4.89038e-07
[2019-08-05 15:35:50.043] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.53825  [0]	Simstep = 32	T = 0.000633484	U_pot = -2.15185	p = 4.8743e-07
[2019-08-05 15:35:50.110] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.60326  [0]	Simstep = 33	T = 0.000633446	U_pot = -2.15206	p = 4.86148e-07
[2019-08-05 15:35:50.173] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.66778  [0]	Simstep = 34	T = 0.00063341	U_pot = -2.15211	p = 4.85339e-07
[2019-08-05 15:35:50.238] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.7335   [0]	Simstep = 35	T = 0.000633375	U_pot = -2.15205	p = 4.84934e-07
[2019-08-05 15:35:50.304] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.80045  [0]	Simstep = 36	T = 0.000633342	U_pot = -2.15195	p = 4.84806e-07
[2019-08-05 15:35:50.375] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.86784  [0]	Simstep = 37	T = 0.00063331	U_pot = -2.15177	p = 4.8502e-07
[2019-08-05 15:35:50.437] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.93054  [0]	Simstep = 38	T = 0.000633281	U_pot = -2.15155	p = 4.85475e-07
[2019-08-05 15:35:50.499] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
INFO:	20190805T153550 3.9941   [0]	Simstep = 39	T = 0.000633255	U_pot = -2.15122	p = 4.86301e-07
[2019-08-05 15:35:50.566] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153550 4.16245  [0]	Simstep = 40	T = 0.000633193	U_pot = -1.85104	p = 4.49816e-07
[2019-08-05 15:35:50.733] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153550 4.2217   [0]	Simstep = 41	T = 0.000633126	U_pot = -1.8505	p = 4.51405e-07
[2019-08-05 15:35:50.791] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153550 4.27963  [0]	Simstep = 42	T = 0.000633106	U_pot = -1.84991	p = 4.53322e-07
[2019-08-05 15:35:50.848] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153550 4.33637  [0]	Simstep = 43	T = 0.000633097	U_pot = -1.84929	p = 4.55453e-07
[2019-08-05 15:35:50.905] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153550 4.39609  [0]	Simstep = 44	T = 0.000633091	U_pot = -1.84864	p = 4.57791e-07
[2019-08-05 15:35:50.966] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153550 4.45968  [0]	Simstep = 45	T = 0.000633088	U_pot = -1.84798	p = 4.60293e-07
[2019-08-05 15:35:51.030] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153551 4.52258  [0]	Simstep = 46	T = 0.000633086	U_pot = -1.84722	p = 4.63085e-07
[2019-08-05 15:35:51.095] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153551 4.58487  [0]	Simstep = 47	T = 0.000633086	U_pot = -1.84645	p = 4.66018e-07
[2019-08-05 15:35:51.157] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153551 4.64571  [0]	Simstep = 48	T = 0.000633087	U_pot = -1.84564	p = 4.69154e-07
[2019-08-05 15:35:51.217] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153551 4.70581  [0]	Simstep = 49	T = 0.00063309	U_pot = -1.84479	p = 4.72466e-07
[2019-08-05 15:35:51.245] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 4.79194  [0]	Simstep = 50	T = 0.00063318	U_pot = -1.50553	p = 4.45505e-07
[2019-08-05 15:35:51.361] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 4.8446   [0]	Simstep = 51	T = 0.000633281	U_pot = -1.50522	p = 4.46828e-07
[2019-08-05 15:35:51.413] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 4.89675  [0]	Simstep = 52	T = 0.000633306	U_pot = -1.50488	p = 4.48088e-07
[2019-08-05 15:35:51.466] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 4.94995  [0]	Simstep = 53	T = 0.000633314	U_pot = -1.50464	p = 4.49164e-07
[2019-08-05 15:35:51.522] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 5.00541  [0]	Simstep = 54	T = 0.000633318	U_pot = -1.50435	p = 4.50317e-07
[2019-08-05 15:35:51.575] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 5.05838  [0]	Simstep = 55	T = 0.00063332	U_pot = -1.50403	p = 4.51538e-07
[2019-08-05 15:35:51.627] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 5.10988  [0]	Simstep = 56	T = 0.000633321	U_pot = -1.50375	p = 4.52708e-07
[2019-08-05 15:35:51.679] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 5.16292  [0]	Simstep = 57	T = 0.00063332	U_pot = -1.50346	p = 4.53928e-07
[2019-08-05 15:35:51.732] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 5.21544  [0]	Simstep = 58	T = 0.000633318	U_pot = -1.50321	p = 4.5512e-07
[2019-08-05 15:35:51.783] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153551 5.26571  [0]	Simstep = 59	T = 0.000633315	U_pot = -1.50289	p = 4.56454e-07
[2019-08-05 15:35:51.804] [AutoPasLog] [debug] Skip not applicable configuration {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Structure-of-Arrays , Newton 3: disabled}
[2019-08-05 15:35:51.805] [AutoPasLog] [debug] Skip not applicable configuration {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Structure-of-Arrays , Newton 3: enabled}
[2019-08-05 15:35:51.805] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153551 5.39639  [0]	Simstep = 60	T = 0.000633074	U_pot = -1.83925	p = 5.15749e-07
[2019-08-05 15:35:51.967] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153551 5.45864  [0]	Simstep = 61	T = 0.0006328	U_pot = -1.83732	p = 5.2306e-07
[2019-08-05 15:35:52.029] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.52129  [0]	Simstep = 62	T = 0.000632748	U_pot = -1.83536	p = 5.30935e-07
[2019-08-05 15:35:52.093] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.58514  [0]	Simstep = 63	T = 0.000632745	U_pot = -1.83328	p = 5.39264e-07
[2019-08-05 15:35:52.155] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.64788  [0]	Simstep = 64	T = 0.000632754	U_pot = -1.83118	p = 5.47783e-07
[2019-08-05 15:35:52.216] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.7076   [0]	Simstep = 65	T = 0.00063277	U_pot = -1.82903	p = 5.56557e-07
[2019-08-05 15:35:52.277] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.76653  [0]	Simstep = 66	T = 0.000632792	U_pot = -1.82682	p = 5.65542e-07
[2019-08-05 15:35:52.338] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.83068  [0]	Simstep = 67	T = 0.000632819	U_pot = -1.82456	p = 5.74728e-07
[2019-08-05 15:35:52.399] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.89015  [0]	Simstep = 68	T = 0.000632852	U_pot = -1.82226	p = 5.84091e-07
[2019-08-05 15:35:52.460] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153552 5.95047  [0]	Simstep = 69	T = 0.000632891	U_pot = -1.81994	p = 5.93592e-07
[2019-08-05 15:35:52.489] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.03803  [0]	Simstep = 70	T = 0.000632979	U_pot = -1.50414	p = 4.88315e-07
[2019-08-05 15:35:52.607] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.09012  [0]	Simstep = 71	T = 0.000633046	U_pot = -1.5032	p = 4.92039e-07
[2019-08-05 15:35:52.659] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.14224  [0]	Simstep = 72	T = 0.000633064	U_pot = -1.50227	p = 4.95655e-07
[2019-08-05 15:35:52.711] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.19481  [0]	Simstep = 73	T = 0.000633073	U_pot = -1.50136	p = 4.99203e-07
[2019-08-05 15:35:52.763] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.24634  [0]	Simstep = 74	T = 0.000633081	U_pot = -1.50043	p = 5.02755e-07
[2019-08-05 15:35:52.815] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.29879  [0]	Simstep = 75	T = 0.000633089	U_pot = -1.49956	p = 5.06171e-07
[2019-08-05 15:35:52.867] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.35163  [0]	Simstep = 76	T = 0.000633098	U_pot = -1.49866	p = 5.09606e-07
[2019-08-05 15:35:52.921] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.40469  [0]	Simstep = 77	T = 0.000633107	U_pot = -1.49784	p = 5.1286e-07
[2019-08-05 15:35:52.973] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153552 6.45608  [0]	Simstep = 78	T = 0.000633115	U_pot = -1.49704	p = 5.16059e-07
[2019-08-05 15:35:53.026] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153553 6.51003  [0]	Simstep = 79	T = 0.000633124	U_pot = -1.49634	p = 5.19059e-07
[2019-08-05 15:35:53.048] [AutoPasLog] [debug] Skip not applicable configuration {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
[2019-08-05 15:35:53.048] [AutoPasLog] [debug] Skip not applicable configuration {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c18 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
[2019-08-05 15:35:53.048] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 6.62981  [0]	Simstep = 80	T = 0.000632907	U_pot = -1.78724	p = 7.3017e-07
[2019-08-05 15:35:53.198] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 6.68332  [0]	Simstep = 81	T = 0.00063272	U_pot = -1.7839	p = 7.4344e-07
[2019-08-05 15:35:53.252] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 6.73682  [0]	Simstep = 82	T = 0.000632786	U_pot = -1.78064	p = 7.56821e-07
[2019-08-05 15:35:53.305] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 6.79111  [0]	Simstep = 83	T = 0.000632911	U_pot = -1.7775	p = 7.69888e-07
[2019-08-05 15:35:53.362] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 6.84656  [0]	Simstep = 84	T = 0.000633055	U_pot = -1.77458	p = 7.82405e-07
[2019-08-05 15:35:53.416] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 6.90154  [0]	Simstep = 85	T = 0.000633207	U_pot = -1.77176	p = 7.94501e-07
[2019-08-05 15:35:53.472] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 6.95745  [0]	Simstep = 86	T = 0.000633364	U_pot = -1.76904	p = 8.06164e-07
[2019-08-05 15:35:53.530] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 7.01504  [0]	Simstep = 87	T = 0.000633523	U_pot = -1.76643	p = 8.17374e-07
[2019-08-05 15:35:53.586] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 7.07071  [0]	Simstep = 88	T = 0.00063368	U_pot = -1.76406	p = 8.279e-07
[2019-08-05 15:35:53.640] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: disabled}
INFO:	20190805T153553 7.12407  [0]	Simstep = 89	T = 0.000633834	U_pot = -1.76174	p = 8.38058e-07
[2019-08-05 15:35:53.663] [AutoPasLog] [debug] Skip not applicable configuration {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Array-of-Structures , Newton 3: enabled}
[2019-08-05 15:35:53.663] [AutoPasLog] [debug] Skip not applicable configuration {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Structure-of-Arrays , Newton 3: disabled}
[2019-08-05 15:35:53.663] [AutoPasLog] [debug] Skip not applicable configuration {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-c01 , Data Layout: Structure-of-Arrays , Newton 3: enabled}
[2019-08-05 15:35:53.663] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletListsCells , CellSizeFactor: 1.000000 , Traversal: verlet-sliced , Data Layout: Array-of-Structures , Newton 3: enabled}
INFO:	20190805T153553 7.20919  [0]	Simstep = 90	T = 0.000633648	U_pot = 
```
**Expected behavior**
All results are the same.

### PR DESCRIPTION
**Pull request by SteffenSeckler**
# Description

- [x] Removes a couple of default values from traversals and TraversalInfo to make sure that they are properly passed.
- [x] Fixes AosNoN3 using proper sorting for processCellAoS in CellFunctor (significant speedup mainly for DirectSum)
- [x] Fixes missing passed skin for VerletListGeneratorFunctor (VerletListsCells.h)
- [x] Fixes sorting of linked-cells breaking the verlet lists cells.
- [x] Removes sph-traversals example

## Resolved Issues

- [x] fixes #327

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] local tests
- [x] Jenkins
- [x] ls1

### CODE REVIEW

**Comment by SteffenSeckler** [comment]
@Garfield96 the directsum performance with sorting (AoS) and disabled N3 should get a significant speedup with this PR! Potentially twice as much better than without sorting, compared to before, so you might want to check this :)

File: tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp [hunk 1]
```diff
@@ -3,7 +3,7 @@
  * @author nguyen
  * @date 02.09.18
  */
-
+#define protected public
```
Comment (Garfield96) [inline tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp]: Nice solution

File: src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h [hunk 2]
```diff
@@ -101,20 +101,23 @@ class VerletListsCells
...
     }
 
-    typename verlet_internal::VerletListGeneratorFunctor f(_neighborLists, _cellMap, this->getCutoff());
+    typename verlet_internal::VerletListGeneratorFunctor f(_neighborLists, _cellMap,
+                                                           this->getCutoff() + this->getSkin());
 
     switch (_buildTraversal) {
       case c08: {
         if (useNewton3) {
           auto buildTraversal = C08Traversal<LinkedParticleCell, typename verlet_internal::VerletListGeneratorFunctor,
```
Comment (Garfield96) [inline src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h]: This pattern occurs 5 times. We should move this to a template function, which uses the traversal type as template parameter.

**Comment by Garfield96** [comment]
Thanks for the changes. I'll benchmark the results.

**Comment by Garfield96** [comment]
@SteffenSeckler The results are great:
result

File: tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp (hunk 1 above)
Comment (FG-TUM) [reply tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp]: I disagree. I would prefer adding a `VerletListsCells::getCellLength()`.

File: tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp [hunk 3]
```diff
@@ -3,7 +3,7 @@
  * @author nguyen
  * @date 26.09.18
  */
-
+#define protected public
```
Comment (FG-TUM) [inline tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp]: same as above

File: src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h (hunk 2 above)
Comment (SteffenSeckler) [reply src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h]: reduced it to two times, using static bool selector.
further code reduction using decltype
