### PR TITLE
Change INIT_RADIUS of ActiveHarmony to fix #500

### LINKED ISSUE #499: Container update in VerletClusterLists takes too long
**Problem**
The container update with the container VerletClusterLists takes too long. This makes configuration with this container very inefficient and slows a simulation down.

**To Reproduce**
1. Run SpinodalDecomposition_equilibration.yaml (and in this case tuning-strategy predictiveTuning) on the CoolMUC2
2. See output

**Example**
Iteration 154
[2020-06-20 **03:30:23.112**] [AutoPasLog] [debug] Skipping container update.
[2020-06-20 **04:54:33.890**] [AutoPasLog] [debug] Iterating with configuration: {Container: VerletClusterLists , CellSizeFactor: 1.000000 , Traversal: verlet-clusters-coloring , Load Estimator: none , Data Layout: AoS , Newton 3: enabled}
[2020-06-20 04:54:39.940] [AutoPasLog] [debug] IteratePairwise took 6049702737 nanoseconds
Tuning: true
Current Memory usage: 278833 kB
Iteration 155

### LINKED ISSUE #500: activeHarmony crash after longer simulations
**Description**
When running the sph-examples with activeHarmony, the time steps get progressively longer (not in simulation time, I suspect the time is spent in tuning). ```ActiveHarmony::reset: Error connecting to Harmony session.``` thrown after around 120-140 time steps in sph and sph-mpi. On occassion it will not throw the exception, but instead finish the tuning phase. However the slow-down always happens

**To Reproduce**
1. Master branch at commit ```918ce7c356250df60b9a1e217482a0c8d4f7bf0d```. This was commited on June 16th
2. Increase number of time steps in sph-main.cpp or sph-main-mpi.cpp. 
Example values: end_time=1; let loop in sph-main-mpi.cpp::main run to 550. I also decreased dx to 1/28
3. set the tuningStrategy to activeHarmony in AutoPas.h
4. Execute with or without mpirun, doesn't matter.
5. See error

**Build environment:**
* OS: Linux. 5.6.16-1-MANJARO
* Compiler: gcc 10.1.0
* Build System: CMake 3.17.3
* IDE: Clion 2020.1.2

**Additional context**
I suspect that the problem is not dependent on the sph-example specifically, but this is as far as I've tested up until now. I'm also not sure if activeHarmony is supposed to slow down during the tuning phase, but I assume that this is a bug.

### PR DESCRIPTION
**Pull request by SteffenSeckler**
# Description

This changes the INIT_RADIUS parameters of ActiveHarmony from 0.5 to 0.7.

## Resolved Issues

- [x] fixes #500

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Locally

### CODE REVIEW

File: examples/sph/sph-main.cpp [hunk 1]
```diff
@@ -303,6 +303,9 @@ int main() {
   sphSystem.setVerletSkin(skinToCutoffRatio * cutoff);
   sphSystem.setVerletRebuildFrequency(rebuildFrequency);
 
+  //sphSystem.setTuningStrategyOption(autopas::TuningStrategyOption::activeHarmony);
+  //autopas::Logger::get()->set_level(autopas::Logger::LogLevel::debug);
```
Comment (FG-TUM) [inline examples/sph/sph-main.cpp:307]: unused code? either remove or say why it is commented out
