### PR TITLE
verlet cluster cells iterator open mp fix398

### LINKED ISSUE #398: VerletClusterCellsParticleIterator does not handle OpenMP correctly
**Describe the bug**
The VerletClusterCellsParticleIterator is not OpenMP parallel.
With #395 a workaround has been implemented, that fixes the previously wrong behavior (all threads were iterating over all particles) to a behavior that at least is correct (only one thread iterates over all particles, all other threads are idle).

**Expected behavior**
The iterator should provide proper OpenMP support.

**Subtasks**
- [x] fix VerletClusterCellsParticleIterator
- [x] fix VerletClusterCellsRegionParticleIterator

### PR DESCRIPTION
**Pull request by SteffenSeckler**
# Description

Enables proper OpenMP support for:
- [x] VerletClusterCellsParticleIterator
- [x] VerletClusterCellsRegionParticleIterator

## Related Pull Requests

- #395 

## Resolved Issues

- [x] fixes #398 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Adds RegionParticleIteratorTest

### CODE REVIEW

File: src/autopas/containers/verletClusterLists/VerletClusterCellsParticleIterator.h [hunk 1]
```diff
@@ -195,20 +206,40 @@ class VerletClusterCellsRegionParticleIterator
...
+    }
+
+    // 4. set _iteratorWithinOneCell to begin of that cell
+    this->_iteratorWithinOneCell = (*this->_vectorOfCells)[this->_cellId]._particles.begin();
+
+    // 5. adapt _cellEnd to dummies.
+    this->_cellEnd = this->_iteratorWithinOneCell + this->getDummyStartbyIndex(this->_cellId);
+
+    // 6. do a -- to be able to do a ++.
+    --this->_iteratorWithinOneCell;
```
Comment (FG-TUM) [inline src/autopas/containers/verletClusterLists/VerletClusterCellsParticleIterator.h]: the way it is documented here it sounds useless so maybe clarify why you want to do the ++ ;)

File: tests/testAutopas/tests/autopasInterface/IteratorTest.cpp [hunk 2]
```diff
@@ -289,21 +293,30 @@ void IteratorTest::testOpenMPIterators(autopas::ContainerOption containerOption,
...
+                                     : apContainer.begin(behavior);
+    for (auto iter = begin; iter.isValid(); ++iter) {
+      iter->touch();
+      if (behavior == autopas::IteratorBehavior::ownedOnly) {
+        EXPECT_TRUE(iter->isOwned());
+      } else if (behavior == autopas::IteratorBehavior::haloOnly) {
+        EXPECT_FALSE(iter->isOwned());
+      }
     }
   }
```
Comment (FG-TUM) [inline tests/testAutopas/tests/autopasInterface/IteratorTest.cpp]: should we move the `#endif` to the end of the block? If `omp` is not defined we test the same thing twice.
