### PR TITLE
Make getNearbyHaloCells reserve

### LINKED ISSUE #890: CellBlock3D::getNearbyHaloCells() does not reserve
**Describe the bug**
`CellBlock3D::getNearbyHaloCells()` calls `push_back()`in a loop without reserving leading to millions of allocations.

**To Reproduce**
Run a simulation with vtune memory consumption analysis.

**Expected behavior**
Best case: only one allocation by introducing a good heuristic. Worst case sum over the distances between low and high index3D.

**Additional context**
Shouldn't we be able to use `ParticleCell::getPossibleParticleOwnerships()` to identify the cell as a halo cell here?

### PR DESCRIPTION
**Pull request by FG-TUM**
# Description

- [x] use cell information to identify halo cells
- [x] `reserve` before `push_back`
- [x] Doc and renaming.

All actual code changes are inside of `getNearbyHaloCells()`.

## Resolved Issues

- [x] fixes #890 

# How Has This Been Tested?

- [x] CI

### CODE REVIEW

File: src/autopas/containers/CellBlock3D.h [hunk 1]
```diff
@@ -278,9 +273,19 @@ class CellBlock3D : public CellBorderAndFlagManager {
...
+   */
+  [[nodiscard]] std::array<index_t, 3> oneToThreeD(index_t index1D) const;
 
-  [[nodiscard]] index_t index1D(const std::array<index_t, 3> &index3d) const;
+  /**
+   * Transform a 3D index to a 1D index in the context of this cell block.
+   * @param index3D
+   * @return 1D cell index.
+   */
+  [[nodiscard]] index_t threeToOneD(const std::array<index_t, 3> &index3D) const;
```
Comment (SamNewcome) [inline src/autopas/containers/CellBlock3D.h:288]: What is meant by "context"

File: src/autopas/containers/CellBlock3D.h [hunk 2]
```diff
@@ -300,15 +305,17 @@ class CellBlock3D : public CellBorderAndFlagManager {
 
   std::array<double, 3> _cellLength{};
 
-  // 1 over above. Since this value is needed for sorting particles in cells, it
-  // is computed quite often
+  /**
+   * 1/_cellLength
+   * Since this value is needed for sorting particles in cells, it is computed quite often.
```
Comment (SamNewcome) [inline src/autopas/containers/CellBlock3D.h:310]:
```suggestion
   * Since this value is often needed for sorting particles in cells, we precompute it.
```

**Review by SamNewcome — CHANGES_REQUESTED** [review]
Just documentation/comment suggestions

File: src/autopas/containers/CellBlock3D.h (hunk 1 above)
Comment (FG-TUM) [reply src/autopas/containers/CellBlock3D.h:288]: The context is the current `CellBlock3D` object

File: src/autopas/containers/CellBlock3D.h [hunk 3]
```diff
@@ -106,127 +105,123 @@ class CellBlock3D : public CellBorderAndFlagManager {
...
-      return false;
-    };
+    // x2 for left and right of the cell; +1 for the cell itself
+    const auto interestingCellsPerDim = (2. * allowedDistance / _cellLength) + 1.;
+    const auto interestingCellsBlockSize =
+        interestingCellsPerDim[0] * interestingCellsPerDim[1] * interestingCellsPerDim[2];
+    // This is an overestimation with the upper bound of possible number of cells in the vicinity.
+    // An overestimate is cheaper than many reallocations.
+    // If the size of the overallocation ever becomes a problem we can use vector::shrink_to_fit() before return.
+    closeHaloCells.reserve(interestingCellsBlockSize);
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/autopas/containers/CellBlock3D.h]: true that's a mistake. Fixed -> e4caafe8c

File: src/autopas/containers/CellBlock3D.h [hunk 4]
```diff
@@ -106,127 +105,123 @@ class CellBlock3D : public CellBorderAndFlagManager {
...
-    if (isHaloCell(index3d)) {
-      closeHaloCells.push_back(&getCell(index3d));
+    // x2 for left and right of the cell; +1 for the cell itself
+    const auto interestingCellsPerDim = utils::ArrayMath::ceilToInt((2. * allowedDistance / _cellLength)) + 1;
+    const auto interestingCellsBlockSize =
+        interestingCellsPerDim[0] * interestingCellsPerDim[1] * interestingCellsPerDim[2];
+    // This is an overestimation with the upper bound of possible number of cells in the vicinity.
+    // An overestimate is cheaper than many reallocations.
+    // If the size of the overallocation ever becomes a problem we can use vector::shrink_to_fit() before return.
+    closeHaloCells.reserve(interestingCellsBlockSize);
```
Comment (manishmishra6016) [inline src/autopas/containers/CellBlock3D.h:202]: I was wondering if we can reserve the size based on `lowIndex3D` and `highIndex3D` that we calculate anyway? Would that offer any benefit (because I am not sure)?

Also, this includes the current cell which we don't need to have, so we could instead have `closeHaloCells.reserve(interestingCellsBlockSize - 1);`? again, not sure if it makes much difference.

**Review by manishmishra6016 — APPROVED** [review]
Everything looks correct and fine, so I am fine if we merge it already :)

File: src/autopas/containers/CellBlock3D.h (hunk 4 above)
Comment (FG-TUM) [reply src/autopas/containers/CellBlock3D.h]: Actually we can. I must have overlooked that when I implemented it, good catch!
-> 21fbfa391

The current cell might be a halo cell so it should be included in the estimate. Anyways it is better to slightly overestimate than to underestimate. Overestimation is basically free but underestimateion potentially costs a reallocation.

File: src/autopas/containers/CellBlock3D.h [hunk 5]
```diff
@@ -106,127 +106,121 @@ class CellBlock3D : public CellBorderAndFlagManager {
...
-   * @param bMin new lower corner of the cellblock
-   * @param bMax new higher corner of the cellblock
-   * @param interactionLength max. radius of interaction between particles
-   * @param cellSizeFactor cell size factor relative to interactionLength
+   * Rebuild the cell block. This resizes the cell block and sets the appropriate internal variables.
+   * @param vec new vector of ParticleCells to which the internal pointer is set.
+   * @param bMin new lower corner of the cell block.
+   * @param bMax new higher corner of the cell block.
+   * @param interactionLength max. radius of interaction between particles.
+   * @param cellSizeFactor cell size factor relative to interactionLength.
```
Comment (thesamriel) [inline src/autopas/containers/CellBlock3D.h:114]:
```suggestion
   * @param vec New vector of ParticleCells to which the internal pointer is set.
   * @param bMin New lower corner of the cell block.
   * @param bMax New higher corner of the cell block.
   * @param interactionLength Max. radius of interaction between particles.
   * @param cellSizeFactor Cell size factor relative to interactionLength.
```

Since you already changed this everywhere else :D

File: src/autopas/containers/CellBlock3D.h [hunk 6]
```diff
@@ -106,127 +106,121 @@ class CellBlock3D : public CellBorderAndFlagManager {
...
     return _cellsPerDimensionWithHalo;
   }
 
   /**
-   * checks whether a given position is inside the halo region of the managed
-   * cell block
-   * @param position the given position
-   * @return true if the position is inside the halo region
+   * Checks whether a given position is inside the halo region of the managed cell block.
+   * @param position the given position.
```
Comment (thesamriel) [inline src/autopas/containers/CellBlock3D.h:169]:
```suggestion
   * @param position The given position.
```

File: src/autopas/containers/CellBlock3D.h [hunk 7]
```diff
@@ -106,127 +106,121 @@ class CellBlock3D : public CellBorderAndFlagManager {
...
-   * @param position cells close to this position are to be returned
-   * @param allowedDistance the maximal distance to the position
-   * @return a container of references to nearby halo cells
+   * Get the halo cells around a given point.
+   * Returns a list of halo cells that are at least partially within allowedDistance of the given position.
+   * If position is inside a halo cell that cell is also returned.
+   * @note The 1 norm is used, i.e. the distance is computed for each dimension separately, aka. Manhattan distance)
+   *
+   * @param position cells close to this position are to be returned.
+   * @param allowedDistance the maximal distance to the position.
```
Comment (thesamriel) [inline src/autopas/containers/CellBlock3D.h:186]:
```suggestion
   * @param position Cells close to this position are to be returned.
   * @param allowedDistance The maximal distance to the position.
```

File: src/autopas/containers/CellBlock3D.h [hunk 8]
```diff
@@ -300,15 +304,17 @@ class CellBlock3D : public CellBorderAndFlagManager {
 
   std::array<double, 3> _cellLength{};
 
-  // 1 over above. Since this value is needed for sorting particles in cells, it
-  // is computed quite often
+  /**
+   * 1/_cellLength
```
Comment (thesamriel) [inline src/autopas/containers/CellBlock3D.h:308]:
```suggestion
   * 1.0 / _cellLength
```

**Review by thesamriel — CHANGES_REQUESTED** [review]
Some Doc fixes for consistency since you already added them in some places.

**Review by thesamriel — APPROVED** [review]

**Review by SamNewcome — APPROVED** [review]
