### PR TITLE
Mirror particles for reflecting

### LINKED ISSUE #713: Particle out of box during fallingDrop simulation
The simulation of fallingDrop interrupts with an runtime_error (particle out of the box)

**To Reproduce**
  run ./md-flexible --yaml-file fallingDrop.yaml in the build directory

**Expected behavior**
  particle should be reflected of the boundaries and the simulation should run without an error.

**Screenshots**
Screenshot from 2023-01-25 11-43-21

**Build environment:**
OS: Linux

### PR DESCRIPTION
**Pull request by SamNewcome**
# Description

Replaces the existing reflecting boundary mechanism with one based on mirror particles. Here 'mirror' particles are placed on the opposite side of a reflecting boundary from an original particle, and the two interact via the standard Lennard-Jones functor. Interactions are limited to when particles are within a range such that any LJ interaction leads to repulsion only.

## Resolved Issues

- [x] fixes #713 
- [x] implements #714 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Standard Reflecting Boundary tests have been modified to test for correct force for the current scheme
- [x] Additional test that checks correct zoning of reflecting boundaries (i.e. that particles react only when it leads to repulsion, for several different sigma values)
- [x] Falling Drop can be run without error.

### CODE REVIEW

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp [hunk 1]
```diff
@@ -39,6 +39,12 @@ RegularGridDecomposition::RegularGridDecomposition(const MDFlexConfig &configura
 
   _decomposition = DomainTools::generateDecomposition(_subdomainCount, configuration.subdivideDimension.value);
 
+  double maxSigma{0};
+  for (auto sigmaMapElement : configuration.sigmaMap.value) {
+    maxSigma = std::max(maxSigma, sigmaMapElement.second);
+  }
```
Comment (FG-TUM) [inline examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:45]:
```suggestion
  double maxSigma{0};
  for (const auto &[_, sigma] : leMap) {
    maxSigma = std::max(maxSigma, sigma);
  }
```

Imho it would be even better to wrap that loop into a lambda function so that `maxSigma` can be turned into a `const` but since the function ends soon after this I'm fine.

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp [hunk 2]
```diff
@@ -39,6 +39,12 @@ RegularGridDecomposition::RegularGridDecomposition(const MDFlexConfig &configura
...
+  _maxReflectiveSkin = sixthRootOfTwo * maxSigma / 2.;
```
Comment (FG-TUM) [inline examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:46]: add a comment explaining this calculation

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp [hunk 3]
```diff
@@ -252,8 +258,11 @@ void RegularGridDecomposition::exchangeMigratingParticles(AutoPasType &autoPasCo
   }
 }
 
-void RegularGridDecomposition::reflectParticlesAtBoundaries(AutoPasType &autoPasContainer) {
+void RegularGridDecomposition::reflectParticlesAtBoundaries(AutoPasType &autoPasContainer,
+                                                            ParticlePropertiesLibraryType &PPL) {
```
Comment (FG-TUM) [inline examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:262]:
```suggestion
void RegularGridDecomposition::reflectParticlesAtBoundaries(AutoPasType &autoPasContainer,
                                                            ParticlePropertiesLibraryType &particlePropertiesLib) {
```
(will require a few more renames)

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp [hunk 4]
```diff
@@ -252,8 +258,11 @@ void RegularGridDecomposition::exchangeMigratingParticles(AutoPasType &autoPasCo
...
   std::array<double, _dimensionCount> reflSkinMin{}, reflSkinMax{};
+  auto functorLJ = autopas::LJFunctor<ParticleType, false, true, autopas::FunctorN3Modes::Newton3Off, false, false>(
```
Comment (FG-TUM) [inline examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:264]:
```suggestion
  auto functorLJ = autopas::LJFunctor<ParticleType, false, true, autopas::FunctorN3Modes::Both, false, false>(
```
Is there a reason to choose a mode different than the default?

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp [hunk 5]
```diff
@@ -262,28 +271,38 @@ void RegularGridDecomposition::reflectParticlesAtBoundaries(AutoPasType &autoPas
...
       for (auto p = autoPasContainer.getRegionIterator(reflSkinMin, reflSkinMax, autopas::IteratorBehavior::owned);
            p.isValid(); ++p) {
-        auto vel = p->getV();
-        // reverse velocity in dimension if towards boundary
-        if ((vel[dimensionIndex] < 0) xor isUpper) {
-          vel[dimensionIndex] *= -1;
+        // Check that particle is within 6th root of 2 * sigma
+        const auto position = p->getR();
+        const auto distanceToBoundary = isUpper ? reflSkinMax[dimensionIndex] - position[dimensionIndex]
+                                                : position[dimensionIndex] - reflSkinMin[dimensionIndex];
```
Comment (FG-TUM) [inline examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:277]:
```suggestion
        const auto distanceToBoundary = std::abs(reflSkinMax[dimensionIndex] - position[dimensionIndex]);
```

**Review by FG-TUM — CHANGES_REQUESTED** [review]
mostly readability suggestions

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp (hunk 4 above)
Comment (SamNewcome) [reply examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:264]: No - other than Newton3On is not needed. But I see no reason why Both is not fine - if N3L is accidentally applied there are no major problems.

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp (hunk 2 above)
Comment (SamNewcome) [reply examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:50]: See latest commit

File: examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp (hunk 5 above)
Comment (SamNewcome) [reply examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:281]: Note, this is not just taking the absolute but takes distance to the two different boundaries, so std::abs will only work in conjunction with the conditional operator, at which point there is no gain in readability (and maybe even a loss).

I can add a comment explaining isUpper, or explaining this step if you feel it is needed.

Comment (FG-TUM) [reply examples/md-flexible/src/domainDecomposition/RegularGridDecomposition.cpp:281]: I overlooked `Min` vs `Max`...

**Review by FG-TUM — APPROVED** [review]
