### PR TITLE
Verlet Cluster Lists Bugfix

### LINKED ISSUE #917: Verlet Cluster Lists appear to result in incorrect forces
**Describe the bug**
When running VCL with exploding liquid, there are explosions (as in problematic ones.

This scenario is the standard exploding liquid, with a verlet skin per timestep of 0.025. This was used, because in earlier runs with LInked Cells and Verlet List Cells, it was found frequently that particles might move ~0.011 per timestep. Running Linked Cells/Verlet List Cells with this new timestep resulted in no fast particle throws. 

Now, when Verlet Cluster Lists are used with this step-size, this verlet skin per timestep is no longer appropriate. The first error is
~~~bash
[2024-07-22 13:41:53.195] [AutoPasLog] [warning] [ParticleBase.h:171] Particle 10325: Distance between old and new position is larger than expected: 0.0007136447901825499 > 0.00015625000000000003
A particle moved farther than verletSkinPerTimestep/2: 0.0267141 > 0.025/2 = 0.0125
Particle
ID      : 10325
Position: [3.98776, 83.9955, 17.821]
Velocity: [3.46025, 4.87561, -4.74658]
Force   : [0, 0, 0]
~~~
meaning a particle was able to move significantly faster than expected without prior "moving faster"s. This indicates an error with VCL rather than the chosen verlet skin per timestep.

**To Reproduce**
Run current exploding liquid with only Verlet Cluster Lists C06 Aos (or SoA), newton3=enabled and a larger domain size (see yaml file)

**Expected behavior**
No warnings.

**Build environment (please complete the following information):**
* OS: Linux
* Compiler: gcc11
* Build System: Make, CMake
* CoolMUC2

**Additional context**
Full yaml file:

~~~yaml
# This yaml file is for single-site molecular simulation. Uncomment the Molecules option to run this experiment using
# md-flexible compiled for multi-site molecules.
# container                        :  [LinkedCells, VarVerletListsAsBuild, VerletClusterLists, VerletLists, VerletListsCells, PairwiseVerletLists]
traversal                        :  [vcl_c06]
data-layout                      :  [AoS]
newton3                          :  [enabled]
verlet-rebuild-frequency         :  10
verlet-skin-radius-per-timestep  :  0.025
verlet-cluster-size              :  4
selector-strategy                :  Fastest-Mean-Value
tuning-strategies                :  []
tuning-interval                  :  6000
tuning-samples                   :  10
functor                          :  Lennard-Jones
cutoff                           :  2
box-min                          :  [0, 0, 0]
box-max                          :  [30, 120, 30]
cell-size                        :  [1]
deltaT                           :  0.00182367
iterations                       :  12000
boundary-type                    : [periodic, periodic, periodic]
Sites:
  0:
    epsilon                      :  1.
    sigma                        :  1.
    mass                         :  1.
# Uncomment below to run a multi-site simulation.
#Molecules:
#  0:
#    site-types                   :  [ 0 ]
#    relative-site-positions      :  [ [0, 0, 0 ] ]
#    moment-of-inertia            :  [ 1., 1., 1. ]
Objects:
  CubeClosestPacked:
    0:
      particle-type-id           :  0
      box-length                 :  [30, 12, 30]
      bottomLeftCorner           :  [0, 54, 0]
      particle-spacing           :  1.
      velocity                   :  [0, 0, 0]
no-end-config                    :  true
no-progress-bar                  :  true


~~~

### PR DESCRIPTION
**Pull request by dmartin13**
# Description

This PR is intended to fix a bug with the Verlet Cluster Lists. 
Particles were not sorted into the correct towers when recreating the neighborlists. The problem was that the order in which out-of-bound particles of the tower were collected and the resizing of the towerblock was wrong. The out-of-bound particles were collected first, then the tower block (and thus also the bounding boxes of the tower) were recalculated. However, the out-of-bounds particles should be collected only after the new tower bounding boxes have been calculated.

## Resolved Issues

- [x] fixes #917 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

The scenario from #917 with a single thread was used. The results for VCL and linked cells were compared (particle interactions and resulting forces). A python script was used that calculates possible differences in the particle interactions from the log output of the calculation with both containers. After the bugfix, there are no more differences between the two containers. The same particle interactions and the same forces are calculated.

### CODE REVIEW

File: src/autopas/containers/verletClusterLists/VerletClusterListsRebuilder.h [hunk 1]
```diff
@@ -86,8 +86,8 @@ class VerletClusterListsRebuilder {
     const auto numTowersNew = numTowersPerDim[0] * numTowersPerDim[1];
 
     // collect all particles that are now not in the right tower anymore
-    auto invalidParticles = collectOutOfBoundsParticlesFromTowers();
-    // collect all remaining particles that are not yet assigned to towers
+    std::vector<std::vector<Particle>> invalidParticles;
+    //  collect all particles that are not yet assigned to towers
     invalidParticles.push_back(std::move(_particlesToAdd));
```
Comment (FG-TUM) [inline src/autopas/containers/verletClusterLists/VerletClusterListsRebuilder.h:91]:
```suggestion
    std::vector<std::vector<Particle>> invalidParticles{};
    // Reserve for:
    //   - _particlesToAdd (+1)
    //   - surplus towers (+max(0, numTowersNew - numTowersOld))
    //   - particles out of bounds of new towers (+numTowersNew)
    invalidParticles.reserve(1 + std::max(0, static_cast<int>(numTowersOld) - static_cast<int>(numTowersNew)) + numTowersNew)
    // collect all particles that are not yet assigned to towers
    invalidParticles.push_back(std::move(_particlesToAdd));
```

- [x] formatting
- [x] reserve before `push_back` / `insert`
- [x] casts before substracting unsigned integers

...should be right I think?

**Review by FG-TUM — CHANGES_REQUESTED** [review]
Very nice catch! While we are at it we should improve the memory allocation.

**Review by FG-TUM — APPROVED** [review]
