### PR TITLE
Remove global force reset from updateForces

### LINKED ISSUE #885: md-flexible applies global forces twice
**Describe the bug**
md-flexible applies globals twice:

1. In `updatePositions`, the forces are reset to the global force.
2. In `updateForces`, the global force is added to the existing forces

Two possible solutions:

1. Remove the global addition from `updateForces`. Advantage is that `updatePositions` (which calls `TimeDiscretization::calculatePositionsAndResetForces`) handles the position update and force reset, and the update of the old force buffer in one for loop over all particles. The disadvantage is that the handling of forces is not handled entirely by `update forces`. For this solution, rename `updateForces` to something that includes the forces.
2. Remove the global force handling from `TimeDiscretization::calculatePositionsAndResetForces` and put it into the `updateForces`. It would also make sense to move the updating of `OldF` to `updateForces` as well.

### PR DESCRIPTION
**Pull request by dmartin13**
# Description

MD-flexible added the global forces to the particles twice. Once in `TimeDiscretization::calculatePositionsAndResetForces` and once in `updateForces`.
The addition of the global forces in `updateForces` has been removed, as `TimeDiscretization::calculatePositionsAndResetForces` iterates over the particles in a loop anyway. This saves further iteration over the particles in `updateForces`.
To make the names of the functions a little more intuitive, `Simulation::updatePositions` has been renamed `Simulation::updatePositionsAndResetForces`. `Simulation::updateForces` has been renamed `Simulation::updateInteractionForces`.

Since we do not have access to the timers in `TimeDiscretization::calculatePositionsAndResetForces`, the timer for setting the global forces has been removed.

## Resolved Issues

- [x] fixes #885 

# How Has This Been Tested?

- [x] Existing tests

### CODE REVIEW

**Review by SamNewcome — APPROVED** [review]

File: examples/md-flexible/src/Simulation.h [hunk 1]
```diff
@@ -251,7 +246,7 @@ class Simulation {
   /**
    * Updates the position of particles in the local AutoPas container.
```
Comment (SamNewcome) [inline examples/md-flexible/src/Simulation.h:247]: Modify this comment

**Review by SamNewcome — CHANGES_REQUESTED** [review]

File: examples/md-flexible/src/Simulation.h (hunk 1 above)
Comment (dmartin13) [reply examples/md-flexible/src/Simulation.h]: done in [d6a43cc](https://github.com/AutoPas/AutoPas/pull/905/commits/d6a43cca1508fbfd43a46ec8ed39b59d55e687aa)

**Review by SamNewcome — APPROVED** [review]
