### PR TITLE
fixes RegionParticleIterator when using a non-default IteratorBehavior

### LINKED ISSUE #142: RegionParticleIterator broken for many threads
**Describe the bug**
RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo failes once at least 32 threads are used.

**To Reproduce**
1. Compile with openmp support
2. Run the tests

**Expected behavior**
Test does not fail.

**Screenshots/Error Reports**
```
➜  cmake-debug git:(feature/regionparticleiteratortestverbose) OMP_NUM_THREADS=31 ctest -R RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo
Test project /home/seckler/work_documents/AutoPas/build/cmake-debug
    Start 91: RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo
1/1 Test #91: RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo ...   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.02 sec
➜  cmake-debug git:(feature/regionparticleiteratortestverbose) OMP_NUM_THREADS=32 ctest -R RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo
Test project /home/seckler/work_documents/AutoPas/build/cmake-debug
    Start 91: RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo
1/1 Test #91: RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo ...***Failed    0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec

The following tests FAILED:
	 91 - RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo (Failed)
Errors while running CTest
➜  cmake-debug git:(feature/regionparticleiteratortestverbose) OMP_NUM_THREADS=33 ctest -R RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo
Test project /home/seckler/work_documents/AutoPas/build/cmake-debug
    Start 91: RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo
1/1 Test #91: RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo ...***Failed    0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec

The following tests FAILED:
	 91 - RegionParticleIteratorTest.testLinkedCellsRegionParticleIteratorBehaviorHalo (Failed)
Errors while running CTest
```

**Additional context**
See e.g. http://vmbungartz10.informatik.tu-muenchen.de/mardyn/blue/organizations/jenkins/AutoPas-Multibranch/detail/feature%2Fregionparticleiteratortestverbose/1/pipeline/249

### PR DESCRIPTION
**Pull request by SteffenSeckler**
# Description
Fixes RegionParticleIterators pointing to wrong cells, when iterating over halo or own cells using IteratorBehavior::haloOnly or IteratorBehavior::ownedOnly.

## Resolved Issues # (issue)
- [x] fixes #142 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Adds multiple additional tests for Linked Cells using different, but fixed numbers of threads (1, 16, 32, 50, 200)

### CODE REVIEW

File: tests/testAutopas/RegionParticleIteratorTest.cpp [hunk 1]
```diff
@@ -65,22 +103,66 @@ TEST_F(RegionParticleIteratorTest, testLinkedCellsRegionParticleIteratorBehavior
   for (auto iterator = lcContainer.getRegionIterator(testRegionMin, _regionMax, autopas::IteratorBehavior::haloOnly);
        iterator.isValid(); ++iterator) {
     iterator->touch();
+    EXPECT_TRUE(utils::inBox(iterator->getR(), testRegionMin, _regionMax)
```
Comment (FG-TUM) [inline tests/testAutopas/RegionParticleIteratorTest.cpp]: Create a bool for this condition for readability (especially of gtest output on case of fail)

File: tests/testAutopas/RegionParticleIteratorTest.cpp [hunk 2]
```diff
@@ -65,22 +103,66 @@ TEST_F(RegionParticleIteratorTest, testLinkedCellsRegionParticleIteratorBehavior
...
   // check the touch using the normal iterator
   for (auto iterator = lcContainer.begin(); iterator.isValid(); ++iterator) {
-    //  std::cout << "id: " << iterator->getID() << " at [" <<
-    //  iterator->getR()[0]
-    //         << ", " << iterator->getR()[1] << ", " << iterator->getR()[2]
-    //              << "] touched:" << iterator->getNumTouched() << std::endl;
-
+    // this is a test for halo only! so we first check whether it's within our region of interest and then whether it's
+    // not in the halo
     EXPECT_EQ(utils::inBox(iterator->getR(), testRegionMin, _regionMax)
```
Comment (FG-TUM) [inline tests/testAutopas/RegionParticleIteratorTest.cpp]: Create a variable for this condition for readability (especially of gtest output on case of fail)

Comment (SteffenSeckler) [reply tests/testAutopas/RegionParticleIteratorTest.cpp]: https://github.com/AutoPas/AutoPas/pull/143/commits/9c1a93fa659df430846823bb885d3291ad059715

File: tests/testAutopas/RegionParticleIteratorTest.cpp (hunk 1 above)
Comment (SteffenSeckler) [reply tests/testAutopas/RegionParticleIteratorTest.cpp]: https://github.com/AutoPas/AutoPas/pull/143/commits/9c1a93fa659df430846823bb885d3291ad059715
