### PR TITLE
Strategy pattern

### LINKED ISSUE #52: IteratePairwiseAoS2 and iteratePairwiseSoA2 should always be called
**Describe the bug**
`iteratePairwiseAoS2` and `iteratePairwiseSoA2` should always be called instead of
`iteratePairwiseAoS` and `iteratePairwiseSoA` should always be called.
The functions with a `2` provide a method to call the functions using the functor as template argument.

This can only be done if the type of the particle container is known.

**Suggestion**
completely remove the interface of `iteratePairwiseAoS` and `iteratePairwiseSoA` and identify the different containers on runtime, but with a static decision tree:

```C++
template<class Functor>
void AutoPas::iteratePairwise2(Functor *f, autopas::DataLayoutOption dataLayoutOption) {
  ...
  if (auto &cont = dynamic_cast<VerletLists<Particle, ParticleCell> &>(*container)) {
    cont.iteratePairwise2(...);
  }
  else if (auto &cont = dynamic_cast<LinkedCells<Particle, ParticleCell> &>(*container)) {
    cont.iteratePairwise2(...);
  }
  else if (auto &cont = dynamic_cast<DirectSum<Particle, ParticleCell> &>(*container)) {
    cont.iteratePairwise2(...);
  }
}
```
this here more or less ignores the other things (dataLayoutOption, soa, aos, newton3, ...) so to make it somewhat feasible some template magic might be required to get the in-lining done without too much code.

### PR DESCRIPTION
**Pull request by FG-TUM**
Transforming the code to a strategy pattern to allow autotuning

- [x] creating selectors
- [x] tests for selectors
- [x] when and where call tuning methods
- [x] ~~fix #52~~

Related Issues:
#52 iteratePairwiseAoS/SoA2: When calling iteratePairwise through the AutoTuner we could change s.th. here

### CODE REVIEW

**Comment by FG-TUM** [comment]
more of a request for comment than a merge request (yet)

File: src/containers/ParticleContainerInterface.h [hunk 1]
```diff
@@ -13,8 +13,8 @@
 
 namespace autopas {
 
-// consider multiple inheritance or delegation vor avoidane of virtual call to
-// Functor
+// consider multiple inheritance or delegation to avoid virtual call to Functor
+// FIXME: WRONG DOCUMENTATION
```
Comment (SteffenSeckler) [inline src/containers/ParticleContainerInterface.h]: fixme

File: src/containers/cellPairTraversals/SlicedTraversal.h [hunk 2]
```diff
@@ -122,7 +119,7 @@ inline void SlicedTraversal<ParticleCell, CellFunctor>::traverseCellPairs() {
   // use fallback version if not applicable
   // FIXME: Remove this as soon as other traversals are available
   if (not isApplicable()) {
```
Comment (SteffenSeckler) [inline src/containers/cellPairTraversals/SlicedTraversal.h]: should no longer be needed

File: src/selectors/TraversalSelector.h [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+
+ private:
+  template <class CellFunctor>
+  std::vector<std::unique_ptr<CellPairTraversal<ParticleCell, CellFunctor>>> generateTraversals(
+      CellFunctor &cellFunctor);
+  template <class CellFunctor>
+  std::unique_ptr<CellPairTraversal<ParticleCell, CellFunctor>> chooseOptimalTraversal(
+      std::vector<std::unique_ptr<CellPairTraversal<ParticleCell, CellFunctor>>> &traversals);
+
+  // for each encountered cell processor save the optimal traversal. The cell processor is saved through its hash
```
Comment (SteffenSeckler) [inline src/selectors/TraversalSelector.h]: I do like that idea and way of saving the optimal traversals. 
Can you actually implement a test, on whether a saved optimal traversal is actually reused?

File: src/selectors/TraversalSelector.h [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+
+template <class ParticleCell>
+template <class CellFunctor>
+std::unique_ptr<CellPairTraversal<ParticleCell, CellFunctor>> TraversalSelector<ParticleCell>::chooseOptimalTraversal(
+    std::vector<std::unique_ptr<CellPairTraversal<ParticleCell, CellFunctor>>> &traversals) {
+  // TODO: Autotuning goes here
+  auto optimalTraversal = std::move(traversals.front());
+
+  if (dynamic_cast<C08Traversal<ParticleCell, CellFunctor> *>(optimalTraversal.get()))
+    _optimalTraversalOptions[typeid(CellFunctor).hash_code()] = TraversalOptions::c08;
```
Comment (SteffenSeckler) [inline src/selectors/TraversalSelector.h]: c++11 way is probably
```C++
std::type_index(typeid(CellFunctor))
```

Comment (SteffenSeckler) [reply src/selectors/TraversalSelector.h]: (but it is equivalent)

**Comment by SteffenSeckler** [comment]
from what I see, this looks like a proper way to implement the strategy pattern.
some minor comments (see above).
also #52 is not yet handled

File: src/selectors/ContainerSelector.h [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+  }
+
+  assert(containers.size() > 0);
+  return containers;
+}
+
+template <class Particle, class ParticleCell>
+void ContainerSelector<Particle, ParticleCell>::chooseOptimalContainer(
+    std::vector<std::unique_ptr<ParticleContainer<Particle, ParticleCell>>> containers) {
+  // TODO: Autotuning goes here
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/selectors/ContainerSelector.h]: One could introduce an extra parameter for selecting a tuner or apply the strategy pattern again and pass a pointer to a tuner.
(And then do tuning over the tuners :D)

[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/selectors/ContainerSelector.h]: In particular, I think it would make sense to create the CellFunctor here and then call iteratePairwise with it. This would remove the need for an AoS and SoA version. Also, a selector/tuner for Newton3 and Data structure could then be plugged in here. The cell functor could then be thrown at a decision tree like you suggested in #52 .
@SteffenSeckler opinions?

File: src/selectors/AutoTuner.h [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+      //      _containerSelector.getOptimalContainer()->iteratePairwiseSoA(cellFunctor);
+      _containerSelector.getOptimalContainer()->iteratePairwiseSoA(f, useNewton3);
+    }
+  } else {
+    if (useNewton3) {
+      CellFunctor<Particle, ParticleCell, ParticleFunctor, false, true> cellFunctor(f);
+      //      if (_iterationsSinceTuning == _tuningInterval)
+      //        tune(cellFunctor);
+      //      _containerSelector.getOptimalContainer()->iteratePairwiseAoS(cellFunctor);
+      _containerSelector.getOptimalContainer()->iteratePairwiseAoS(f, useNewton3);
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/selectors/AutoTuner.h]: In particular, I think it would make sense to create the CellFunctor here and then call iteratePairwise with it. This would remove the need for an AoS and SoA version. Also, a selector/tuner for Newton3 and Data structure could then be plugged in here. The cell functor could then be thrown at a decision tree like you suggested in #52 .
@SteffenSeckler opinions?

File: src/containers/ParticleContainerInterface.h (hunk 1 above)
Comment (FG-TUM) [reply src/containers/ParticleContainerInterface.h]: 9eb6d463b99bbd6c3ef47c2988be2e4c18277090

File: src/selectors/TraversalSelector.h (hunk 3 above)
Comment (FG-TUM) [reply src/selectors/TraversalSelector.h]: I do not really know how since the returned traversals are always new objects. Therefore I would need to check if indeed the else branch in `getOptimalTraversal` is selected because it would obviously return the same traversal for the same type of cellFunctor even when going through the whole selection process again. Can this be tested via mocks?
At least when looking into it with gdb it works as intended :)

File: src/selectors/AutoTuner.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (SteffenSeckler) [reply src/selectors/AutoTuner.h]: #52 is now solved by #64 so please don't do the work twice :) but just use the macro.

File: src/containers/cellPairTraversals/SlicedTraversal.h (hunk 2 above)
Comment (FG-TUM) [reply src/containers/cellPairTraversals/SlicedTraversal.h]: 866924523f0f501f9c7dee2959365be3da234841

**Comment by FG-TUM** [comment]
Further thoughts open for discussion:

1. I don't think we need to rebuild all containers for tuning since we do not want to test all options anyway. 
2. Decisions like Newton3, useSoA, VerletSkinRange etc should be delegated to dedicated selectors.

File: src/containers/cellPairTraversals/SlicedTraversal.h [hunk 7]
```diff
@@ -95,37 +97,14 @@ inline void SlicedTraversal<ParticleCell, CellFunctor>::rebuild(std::vector<Part
...
+inline void SlicedTraversal<ParticleCell, PairwiseFunctor, useSoA, useNewton3>::traverseCellPairs(
+    std::vector<ParticleCell> &cells) {
   using std::array;
 
   auto numSlices = _sliceThickness.size();
   // 0) check if applicable
 
-  // use fallback version if not applicable
-  // FIXME: Remove this as soon as other traversals are available
-  if (not isApplicable()) {
```
Comment (SteffenSeckler) [inline src/containers/cellPairTraversals/SlicedTraversal.h]: maybe throw an exception if it isn't applicable. just to prevent it being called when it isn't applicable

File: src/selectors/AutoTuner.h [hunk 8]
```diff
@@ -0,0 +1,126 @@
...
+  auto container = _containerSelector.getOptimalContainer();
+
+  /// @todo: WANT one single iteratePairwise(CellFunctor) for containers
+  /// @todo: CellFunctor for iteration should be build here using selectors for SoA and N3
+  if (useSoA) {
+    if (useNewton3) {
+      if (_iterationsSinceTuning >= _tuningInterval) {
+        tune<ParticleFunctor, true, true>(*f);
+      }
+      WithStaticContainerType(container, container->iteratePairwiseSoA(f, useNewton3););
```
Comment (SteffenSeckler) [inline src/selectors/AutoTuner.h]: move these statements behind all the ifs, to deduplicate code a bit

File: src/selectors/AutoTuner.h [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+    } else {
+      if (_iterationsSinceTuning >= _tuningInterval) {
+        tune<ParticleFunctor, true, false>(*f);
+      }
+      WithStaticContainerType(container, container->iteratePairwiseSoA(f, useNewton3););
```
Comment (SteffenSeckler) [inline src/selectors/AutoTuner.h]: same

Comment (SteffenSeckler) [reply src/selectors/AutoTuner.h]: (this can be merged with the previous)

File: src/selectors/ContainerSelector.h [hunk 10]
```diff
@@ -0,0 +1,150 @@
...
+        _optimalContainer(nullptr) {}
+
+  /**
+   * Getter for the optimal container.
+   * @return Smartpointer to the optimal container.
+   */
+  std::shared_ptr<ParticleContainer<Particle, ParticleCell>> getOptimalContainer();
+
+  /**
+   * Evaluates the optimal container option.
```
Comment (SteffenSeckler) [inline src/selectors/ContainerSelector.h]: is this function actually allowed to modify the particles? if it does, there has to be some kind of way to rezero the resulting forces, etc.
-> add new issue

File: src/selectors/ContainerSelector.h [hunk 11]
```diff
@@ -0,0 +1,150 @@
...
+        containers.push_back(std::make_unique<DirectSum<Particle, ParticleCell>>(_boxMin, _boxMax, _cutoff));
+        break;
+      }
+      case linkedCells: {
+        containers.push_back(
+            std::make_unique<LinkedCells<Particle, ParticleCell>>(_boxMin, _boxMax, _cutoff, _allowedTraversalOptions));
+        break;
+      }
+      case verletLists: {
+        // TODO determine verletSkin and verletRebuildFrequency via tuning
```
Comment (SteffenSeckler) [inline src/selectors/ContainerSelector.h]: #36

File: src/selectors/ContainerSelector.h [hunk 12]
```diff
@@ -0,0 +1,150 @@
...
+        containers[containers.size() - 1]->addParticle(*particleIter);
+      }
+      for (auto particleIter = _optimalContainer->begin(IteratorBehavior::haloOnly); particleIter.isValid();
+           ++particleIter) {
+        containers[containers.size() - 1]->addHaloParticle(*particleIter);
+      }
+    }
+  }
+
+  assert(containers.size() > 0);
```
Comment (SteffenSeckler) [inline src/selectors/ContainerSelector.h]: exception

File: src/selectors/TraversalSelector.h [hunk 13]
```diff
@@ -0,0 +1,158 @@
...
+   * @tparam useSoA
+   * @tparam useNewton3
+   * @param pairwiseFunctor The functor that defines the interaction of two particles.
+   * @return Smartpointer to the optimal traversal.
+   */
+  template <class PairwiseFunctor, bool useSoA, bool useNewton3>
+  std::unique_ptr<CellPairTraversal<ParticleCell>> getOptimalTraversal(PairwiseFunctor &pairwiseFunctor);
+
+  /**
+   * Evaluates to optimal traversal based on a given cell functor.
```
Comment (SteffenSeckler) [inline src/selectors/TraversalSelector.h]: "has to reset particles" might also be here

File: src/selectors/TraversalSelector.h [hunk 14]
```diff
@@ -0,0 +1,158 @@
...
+      case TraversalOptions::sliced: {
+        traversals.push_back(std::make_unique<SlicedTraversal<ParticleCell, PairwiseFunctor, useSoA, useNewton3>>(
+            _dims, &pairwiseFunctor));
+        break;
+      }
+      default: { AutoPasLogger->warn("Traversal type {} is not a known type!", option); }
+    }
+  }
+
+  assert(not traversals.empty());
```
Comment (SteffenSeckler) [inline src/selectors/TraversalSelector.h]: exception

File: src/selectors/TraversalSelector.h [hunk 15]
```diff
@@ -0,0 +1,158 @@
...
+
+template <class ParticleCell>
+template <class PairwiseFunctor, bool useSoA, bool useNewton3>
+std::unique_ptr<CellPairTraversal<ParticleCell>> TraversalSelector<ParticleCell>::chooseOptimalTraversal(
+    std::vector<std::unique_ptr<CellPairTraversalInterface>> &traversals) {
+  // remove traversals which are not applicable to the current domain size
+  traversals.erase(
+      std::remove_if(traversals.begin(), traversals.end(), [](auto const &t) { return not t->isApplicable(); }),
+      traversals.end());
+  assert(not traversals.empty());
```
Comment (SteffenSeckler) [inline src/selectors/TraversalSelector.h]: exception

File: src/selectors/TraversalSelector.h [hunk 16]
```diff
@@ -0,0 +1,158 @@
...
+
+  // TODO: Autotuning goes here
+  // Tedious downcast
```
Comment (SteffenSeckler) [inline src/selectors/TraversalSelector.h]: why do you need this downcast?

File: tests/testAutopas/ContainerSelectorTest.cpp [hunk 17]
```diff
@@ -0,0 +1,35 @@
...
+  autopas::ContainerSelector<Particle, FPCell> containerSelectorLC(bBoxMin, bBoxMax, cutoff, verletSkin,
+                                                                   verletRebuildFrequency, optionVectorLC, traversals);
+  autopas::ContainerSelector<Particle, FPCell> containerSelectorVerlet(
+      bBoxMin, bBoxMax, cutoff, verletSkin, verletRebuildFrequency, optionVectorVerlet, traversals);
+
+  auto containerDir = containerSelectorDir.getOptimalContainer();
+  auto containerLC = containerSelectorLC.getOptimalContainer();
+  auto containerVerlet = containerSelectorVerlet.getOptimalContainer();
+
+  ASSERT_TRUE((dynamic_cast<autopas::DirectSum<Particle, FPCell>*>(containerDir.get())));
```
Comment (SteffenSeckler) [inline tests/testAutopas/ContainerSelectorTest.cpp]: change this to EXPECT_TRUE

File: src/AutoPas.h [hunk 18]
```diff
@@ -97,52 +86,42 @@ class AutoPas {
...
-    bool useNewton3 = true;
-    if (newton3Allowed and nonNewton3Allowed) {
-      /// @todo auto-tune (far off future)
-    } else if (not newton3Allowed and not nonNewton3Allowed) {
-      /// @todo throw exception
-    } else {
-      useNewton3 = newton3Allowed;
-    }
+    // @todo remove this and let is be handled via a selector
     switch (dataLayoutOption) {
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/AutoPas.h]: 75d11a5 moved. But long term this should probably go into a dedicated selector.

File: src/containers/LinkedCells.h [hunk 19]
```diff
@@ -34,10 +36,29 @@ class LinkedCells : public ParticleContainer<Particle, ParticleCell, SoAArraysTy
...
    * @param cutoff
+   * @param allowedTraversalOptions Traversal options from which the TraversalSelector shall choose.
+   * By default all applicable traversals are allowed.
    */
-  LinkedCells(const std::array<double, 3> boxMin, const std::array<double, 3> boxMax, double cutoff)
-      : ParticleContainer<Particle, ParticleCell, SoAArraysType>(boxMin, boxMax, cutoff),
-        _cellBlock(this->_data, boxMin, boxMax, cutoff) {}
+  LinkedCells(const std::array<double, 3> boxMin, const std::array<double, 3> boxMax, const double cutoff,
+              const std::vector<TraversalOptions> &allowedTraversalOptions = allLCApplicableTraversals())
+      : ParticleContainer<Particle, ParticleCell, SoAArraysType>(boxMin, boxMax, cutoff, allLCApplicableTraversals()),
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/containers/LinkedCells.h]: No. The Particle container provides an interface to query all applicable traversals. This is needed to check whether the passed allowed traversals are applicable.

File: src/containers/cellPairTraversals/SlicedTraversal.h (hunk 7 above)
Comment (FG-TUM) [reply src/containers/cellPairTraversals/SlicedTraversal.h]: Applicability check is now here:
https://github.com/AutoPas/AutoPas/blob/75d11a55f2b192119544169fee097a1be4d0a511/src/selectors/TraversalSelector.h#L108

So it cannot be called when not applicable.

File: src/containers/cellPairTraversals/C08Traversal.h [hunk 20]
```diff
@@ -73,12 +73,17 @@ inline void C08Traversal<ParticleCell, CellFunctor>::traverseCellPairs() {
...
+            this->processBaseCell(cells, baseIndex);
           }
         }
       }
     }
   }
+}
+
+template <class ParticleCell, class PairwiseFunctor, bool useSoA, bool useNewton3>
+TraversalOptions C08Traversal<ParticleCell, PairwiseFunctor, useSoA, useNewton3>::getName() {
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/containers/cellPairTraversals/C08Traversal.h]: done
4d9cb9baf31ecb5e4fcf563bed8bf73e2e51893d

File: src/selectors/AutoTuner.h (hunk 8 above)
Comment (FG-TUM) [reply src/selectors/AutoTuner.h]: done
20847cfa204630cce4d33a37ef0d3a6788bdd939

File: src/selectors/TraversalSelector.h (hunk 16 above)
Comment (FG-TUM) [reply src/selectors/TraversalSelector.h]: `getOptimalTraversal()` needs to return a pointer to a `CellPairTraversal` so `iteratePairwise` can be called on it.

File: tests/testAutopas/ContainerSelectorTest.cpp (hunk 17 above)
Comment (FG-TUM) [reply tests/testAutopas/ContainerSelectorTest.cpp]: done
d69fffaf59eec7b7b86a0cc3032406ce177a2a61

File: src/selectors/TraversalSelector.h (hunk 15 above)
Comment (FG-TUM) [reply src/selectors/TraversalSelector.h]: done 
ba458f8f4ede49c52aaca008f312039512b58c6f

File: src/selectors/TraversalSelector.h (hunk 14 above)
Comment (FG-TUM) [reply src/selectors/TraversalSelector.h]: done 
ba458f8f4ede49c52aaca008f312039512b58c6f

File: src/selectors/ContainerSelector.h (hunk 12 above)
Comment (FG-TUM) [reply src/selectors/ContainerSelector.h]: done 
ba458f8f4ede49c52aaca008f312039512b58c6f

File: src/containers/LinkedCells.h [hunk 21]
```diff
@@ -34,10 +36,29 @@ class LinkedCells : public ParticleContainer<Particle, ParticleCell, SoAArraysTy
...
+        _cellBlock(this->_cells, boxMin, boxMax, cutoff) {
+    // LC should only be instantiated with applicable traversals
+    assert(this->checkIfTraversalsAreApplicable(allowedTraversalOptions));
+    // LC should not bee instantiated without any traversals
+    assert(not allowedTraversalOptions.empty());
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/containers/LinkedCells.h]: done 
ba458f8f4ede49c52aaca008f312039512b58c6f

File: src/containers/LinkedCells.h [hunk 22]
```diff
@@ -34,10 +36,29 @@ class LinkedCells : public ParticleContainer<Particle, ParticleCell, SoAArraysTy
...
    */
-  LinkedCells(const std::array<double, 3> boxMin, const std::array<double, 3> boxMax, double cutoff)
-      : ParticleContainer<Particle, ParticleCell, SoAArraysType>(boxMin, boxMax, cutoff),
-        _cellBlock(this->_data, boxMin, boxMax, cutoff) {}
+  LinkedCells(const std::array<double, 3> boxMin, const std::array<double, 3> boxMax, const double cutoff,
+              const std::vector<TraversalOptions> &allowedTraversalOptions = allLCApplicableTraversals())
+      : ParticleContainer<Particle, ParticleCell, SoAArraysType>(boxMin, boxMax, cutoff, allLCApplicableTraversals()),
+        _cellBlock(this->_cells, boxMin, boxMax, cutoff) {
+    // LC should only be instantiated with applicable traversals
+    assert(this->checkIfTraversalsAreApplicable(allowedTraversalOptions));
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/containers/LinkedCells.h]: done 
ba458f8f4ede49c52aaca008f312039512b58c6f

File: src/selectors/AutoTuner.h (hunk 9 above)
Comment (FG-TUM) [reply src/selectors/AutoTuner.h]: done
20847cf

File: src/selectors/ContainerSelector.h (hunk 10 above)
Comment (FG-TUM) [reply src/selectors/ContainerSelector.h]: needs to be thought about for the next pull request.

Comment (FG-TUM) [reply src/selectors/ContainerSelector.h]: #71

File: src/selectors/TraversalSelector.h (hunk 13 above)
Comment (FG-TUM) [reply src/selectors/TraversalSelector.h]: #71

File: src/containers/ParticleContainerInterface.h [hunk 23]
```diff
@@ -13,13 +13,13 @@
 
 namespace autopas {
 
-// consider multiple inheritance or delegation vor avoidane of virtual call to
-// Functor
+// consider multiple inheritance or delegation to avoid virtual call to Functor
```
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/containers/ParticleContainerInterface.h]: that was your comment so probably yes :P
