### PR TITLE
Make VerletListsLinkedBase directly inherit from ParticleContainerInterface

### LINKED ISSUE #94: VerletLists should probably inherit from the ParticleContainerInterface directly
**Describe the bug**
Currently the VerletLists inherit from ParticleContainer, thus inheriting the cells and some methods.
The cells are completely unneeded and the methods sometimes work on the cells, so they are often wrong.
It would be easier to inherit from the ParticleContainerInterface, s.t., bugs are harder to make.

### PR DESCRIPTION
**Pull request by SteffenSeckler**
# Description

Changes VerletListsLinkedBase,s.t., it inherits directly from ParticleContainerInterface instead of ParticleContainer.

The methods provided in ParticleContainer and especially the cells are not needed and sometimes produce completely wrong results if not overwritten.

This prevents stupid errors.

## Resolved Issues

- [x] fixes #94

### CODE REVIEW

**Comment by SteffenSeckler** [comment]
checks have passed 😉

File: src/autopas/containers/ParticleContainer.h [hunk 1]
```diff
@@ -38,7 +38,7 @@ class ParticleContainer : public ParticleContainerInterface<ParticleCell> {
       : _cells(), _boxMin(boxMin), _boxMax(boxMax), _cutoff(cutoff), _skin(skin) {}
 
   /**
-   * destructor of ParticleContainer
+   * Destructor of ParticleContainer
```
Comment (FG-TUM) [inline src/autopas/containers/ParticleContainer.h]:
```suggestion
   * Destructor of ParticleContainer.
```
while we are at it :P

File: src/autopas/containers/ParticleContainer.h [hunk 2]
```diff
@@ -102,17 +102,6 @@ class ParticleContainer : public ParticleContainerInterface<ParticleCell> {
    */
   double getInteractionLength() const override final { return _cutoff + _skin; }
 
-  /**
-   * Checks if the given traversals are applicable to this container.
-   * @param traversalOptions
-   * @return True iff traversalOptions is a subset of _applicableTraversals
-   */
-  bool checkIfTraversalsAreApplicable(const std::set<TraversalOption> &traversalOptions) const {
```
Comment (FG-TUM) [inline src/autopas/containers/ParticleContainer.h]: why remove this? Because it was unused?

File: src/autopas/containers/verletClusterLists/VerletClusterLists.h [hunk 3]
```diff
@@ -708,18 +700,13 @@ class VerletClusterLists : public ParticleContainer<FullParticleCell<Particle>>
...
-  std::vector<FullParticleCell<Particle>> _clusters;
-
   /**
    * The number of particles in a full cluster.
    */
   int _clusterSize;
 
   /**
-   * The number of clusters. This is not equal to _clusters.size(), as every grid might contain multiple clusters.
+   * The number of clusters. This is not equal to _cells.size(), as every grid might contain multiple clusters.
```
Comment (FG-TUM) [inline src/autopas/containers/verletClusterLists/VerletClusterLists.h]:
```suggestion
   * The number of clusters. This is not equal to _cells.size(), as every grid (=cell) might contain multiple clusters.
```

File: src/autopas/containers/ParticleContainer.h (hunk 2 above)
Comment (SteffenSeckler) [reply src/autopas/containers/ParticleContainer.h]: yep
