### PR TITLE
Avoid force calculation between halo cells + new getNumberOfParticles

### LINKED ISSUE #718: ParticleContainerInterface::numParticles() probably inconsistent
**Describe the bug**
Currently `numParticles()` seems to report the `size` of particle vectors in cells. This means it would count particles that are marked for deletion (aka dummies). However, ClusterTowers do subtract the number of dummies they insert to fill up the last cluster and other containers might do weird things too.

**Expected behavior**
I see three options:
1. Consistently count **everything**.
2. Count every particle that is not a dummy. (This would probably be in O(N) instead of O(1) as every other solution because we don't track deletion on cell level).
3. Count everything that was part of the simulation. So count particles that are marked as deleted but not those that were inserted for data structure reasons. For the cluster towers this is easy. Not sure about other / future containers.

We should review where the function is used to get a clearer picture what we need. Total particle count is tracked in the `LogicHandler` so the high-level interface is not impacted by this.

No matter which one we choose we should clearly specify what the function does in the documentation.

**Additional context**
While we are at it, rename the function to `getNumberOfParticles()`

### LINKED ISSUE #765: Avoid force calculations between two halo particles
**The problem**
We fully calculate force interactions between halo particles. This is unnecessary computation since we don't use the results.
This is happening at least for all cell-based traversal and potentially also for other algorithms. E.g. we calculate forces between the green halo particles in the image below.

**Solution ideas**
1. The simplest option is adding another if-statement to the functor. We already do this for dummy particles and could also do this if both particles are halo particles.
2. For cell-based containers, halo cells contain purely halo (and maybe dummy) particles. Therefore we could avoid the interactions already in an earlier stage, so we don't load the functor for interactions between halo cells. One possible place would be the CellFunctor. However, we don't have access to the type of the cell at the moment.
3. If this cannot be done in the CellFunctor, maybe the criterion must be implemented for every traversal separately...Please feel free to add

**Additional optimization idea**
Additionally, we make duplicate force calculations between halo and owned particles. In the image below, we call the functor the owned red and blue halo particle, and also for the owned blue and red halo particle. The calculations should be identical and could therefore be saved. But this then requires adding up the forces from the halo particles to their corresponding owned mirrors. This idea comes from the lammps implementation.

**Example image of a cell-based container with periodic boundary conditions:**
image

### PR DESCRIPTION
**Pull request by dmartin13**
# Description

1. **Halo-Interactions**: So far we had no access to the type of a cell (owned, halo-cell or both) in the `CellFunctor` and therefore useless interactions between two halo-cells were calculated. `ParticleCells` contain now an `OwnershipState` that can either be `owned`, `halo`, `ownedOrHalo`(default) or `dummy` (dummy = empty cell). This `OwnershipState` can be set **once** via `setPossibleParticleOwnerships(OwnershipState state)`. Any attempt to add a particle that does not match the `OwnershipState` causes an exception (dummies can be added always). The `OwnershipState` of a cell can be requested via `getPossibleParticleOwnerships()`. In `CellBlock3D` this field is used for all cell-based particle containers to set the `OwnershipState` of cells.
   - Interactions between two pure halo cells are skipped in the `CellFunctor`. 
   - Interactions between a halo cell and any other cell is skipped in the `CellFunctor` if newton3 is off and bidirectional is off
2. **Particle Counters**:
   - `numParticles()` of cells is renamed to `size()`, since this function simply returned the `size()` of the internal particle storage
   - `getNumberOfParticles()` in containers (also for SOAs) is renamed to `size()`, since this function returned the value of `numParticles()` aka `size()`.
   - additionally a new function `getNumberOfParticles(IteratorBehavior behavior = IteratorBehavior::owned)` is introduced that allows to get the actual number of particles with respect to the `OwnershipState` of particles in a cell/container. Note: since this function iterates over the whole internal particle storage it is in O(n) and should only be used when really necessary.

## Resolved Issues

- [x] partially fixes #765: 
  - Interactions between two pure halo cells are skipped in the `CellFunctor`. 
  - Interactions between a halo cell and any other cell is skipped in the `CellFunctor` if newton3 is off and bidirectional is off
- [x] partially fixes #718: 
  - `size()` now returns the number of elements in the internal particle storage (with exception of `ClusterTower`). For `ClusterTower` `size()` returns the number of all particles (owned+halo+dummy) but without trailing dummy particles that are used for data structure reasons.
  - `getNumberOfParticles(IteratorBehavior behavior)` can now be used to get the actual number of particles with a given `IteratorBehavior`

# How Has This Been Tested?

- [x] cells/CellOwnershipTest/testOwnershipFullParticleCell
- [x] cells/CellOwnershipTest/testOwnershipReferenceParticleCell
- [x] cells/CellOwnershipTest/testOwnershipSortedCellView
- [x] cells/CellOwnershipTest/testOwnershipOctreeLeafNode
- [x] container/CellBlock3DTest/testCellOwnership
- [x] container/ParticleCounterTest/testGetNumberOfParticles
- [x] pairwiseFunctors/CellFunctorTest/testOwnedAndHaloCellInteractionPair
- [x] pairwiseFunctors/CellFunctorTest/testOwnedAndHaloCellInteractionSingle

# Experiments

CPU: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz

Test scenario for traversal `lc_c18` (`OMP_NUM_THREADS=1`): 
```
./md-flexible --no-end-config --container LinkedCells --traversal lc_c18 --newton3 enabled --data-layout SoA --particle-generator closestPacking --cutoff 2.5 --particle-spacing 1.2 --box-length 30 --iterations 20
```

Test scenario for traversal `lc_c01` (`OMP_NUM_THREADS=1`): 
```
./md-flexible --no-end-config --container LinkedCells --traversal lc_c01 --newton3 disabled --data-layout SoA --particle-generator closestPacking --cutoff 2.5 --particle-spacing 1.2 --box-length 30 --iterations 20
```

|                              | Commit ID | #Owned after run | #Halo after run | ForceUpdateNonTuning (seconds): lc_c18 | ForceUpdateNonTuning (seconds): lc_c01 |
|------------------------------|-----------|------------------|-----------------|-----------------------------------|-----------------------------------|
| Baseline                     | ca168e8   | 22925            | 32803           | 2.2606                        | 2.4695                        |
| Avoid Halo-Halo Interactions | eeb6565   | 22925            | 32803           | 1.6648                        | 2.4417                        |

With additional parameters `--deltaT 0 --boundary-type none`:
|                              | Commit ID | #Owned after run | #Halo after run | ForceUpdateNonTuning (seconds): lc_c18 | ForceUpdateNonTuning (seconds): lc_c01 |
|------------------------------|-----------|------------------|-----------------|-----------------------------------|-----------------------------------|
| Baseline                     | ca168e8   | 22925            | 0               | 0.9589                         | 1.7262                        |
| Avoid Halo-Halo Interactions | eeb6565   | 22925            | 0               | 0.9553                         | 1.7309                        |

If we avoid halo particle creation the results are similar. So the differences in timings in the first table result from the halo-halo cell interaction avoid.

### CODE REVIEW

File: tests/testAutopas/tests/pairwiseFunctors/CellFunctorTest.h [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+};
+
+template <typename T>
+class CellFunctorTest : public AutoPasTestBase {
+ public:
+  CellFunctorTest() = default;
+
+  ~CellFunctorTest() override = default;
+
+ private:
```
Comment (FG-TUM) [inline tests/testAutopas/tests/pairwiseFunctors/CellFunctorTest.h:36]:
```suggestion
```

File: src/autopas/cells/ParticleCell.h [hunk 2]
```diff
@@ -128,9 +142,50 @@ class ParticleCell {
...
+ protected:
+  /**
+   * The particles which can be contained in this cell are determined by the OwnershipState
+   */
+  OwnershipState _ownershipState{autopas::OwnershipState::owned | autopas::OwnershipState::halo};
+  /**
+   * Flag that is set to true once OwnershipState has been set to avoid resetting the OwnershipState
    */
-  AutoPasLock _cellLock{};
+  bool _ownershipStateSet{false};
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/cells/ParticleCell.h]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: src/autopas/containers/CellBlock3D.h [hunk 3]
```diff
@@ -419,6 +419,22 @@ inline void CellBlock3D<ParticleCell>::rebuild(std::vector<ParticleCell> &vec, c
   for (auto &cell : *_cells) {
     cell.setCellLength(_cellLength);
   }
+
+  // determine the particle types, this cell can contain. This is later used in the CellFunctor to skip calculations
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/containers/CellBlock3D.h]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: src/autopas/containers/LoadEstimators.h [hunk 4]
```diff
@@ -36,8 +36,7 @@ unsigned long squaredParticlesPerCell(const std::vector<ParticleCell> &cells,
   for (unsigned long x = lowerCorner[0]; x <= upperCorner[0]; x++) {
     for (unsigned long y = lowerCorner[1]; y <= upperCorner[1]; y++) {
       for (unsigned long z = lowerCorner[2]; z <= upperCorner[2]; z++) {
-        auto load =
-            cells[autopas::utils::ThreeDimensionalMapping::threeToOneD(x, y, z, cellsPerDimension)].numParticles();
+        auto load = cells[autopas::utils::ThreeDimensionalMapping::threeToOneD(x, y, z, cellsPerDimension)].size();
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/containers/LoadEstimators.h]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: src/autopas/pairwiseFunctors/CellFunctor.h [hunk 5]
```diff
@@ -108,8 +108,14 @@ template <class Particle, class ParticleCell, class ParticleFunctor, DataLayoutO
           bool useNewton3, bool bidirectional>
 void CellFunctor<Particle, ParticleCell, ParticleFunctor, DataLayout, useNewton3, bidirectional>::processCell(
     ParticleCell &cell) {
-  if ((DataLayout == DataLayoutOption::soa && cell._particleSoABuffer.getNumberOfParticles() == 0) ||
-      (DataLayout == DataLayoutOption::aos && cell.numParticles() == 0)) {
+  if ((DataLayout == DataLayoutOption::soa && cell._particleSoABuffer.size() == 0) ||
+      (DataLayout == DataLayoutOption::aos && cell.size() == 0)) {
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/pairwiseFunctors/CellFunctor.h]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: src/autopas/pairwiseFunctors/CellFunctor.h [hunk 6]
```diff
@@ -132,9 +138,21 @@ template <class Particle, class ParticleCell, class ParticleFunctor, DataLayoutO
 void CellFunctor<Particle, ParticleCell, ParticleFunctor, DataLayout, useNewton3, bidirectional>::processCellPair(
 
     ParticleCell &cell1, ParticleCell &cell2, const std::array<double, 3> &sortingDirection) {
-  if ((DataLayout == DataLayoutOption::soa && (cell1._particleSoABuffer.getNumberOfParticles() == 0 ||
-                                               cell2._particleSoABuffer.getNumberOfParticles() == 0)) ||
-      (DataLayout == DataLayoutOption::aos && (cell1.numParticles() == 0 || cell2.numParticles() == 0))) {
+  if ((DataLayout == DataLayoutOption::soa &&
+       (cell1._particleSoABuffer.size() == 0 || cell2._particleSoABuffer.size() == 0)) ||
+      (DataLayout == DataLayoutOption::aos && (cell1.size() == 0 || cell2.size() == 0))) {
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/pairwiseFunctors/CellFunctor.h]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: tests/testAutopas/tests/cells/CellOwnershipTest.cpp [hunk 7]
```diff
@@ -0,0 +1,146 @@
...
+    Molecule po({0.1, 0.1, 0.1}, {0., 0., 0.}, 0);
+    po.setOwnershipState(autopas::OwnershipState::owned);
+
+    Molecule ph({0.2, 0.2, 0.2}, {0., 0., 0.}, 0);
+    ph.setOwnershipState(autopas::OwnershipState::halo);
+
+    Molecule pd({0.3, 0.3, 0.3}, {0., 0., 0.}, 0);
+    pd.setOwnershipState(autopas::OwnershipState::dummy);
+
+    Molecule p1, p2;
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply tests/testAutopas/tests/cells/CellOwnershipTest.cpp]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: tests/testAutopas/tests/cells/CellOwnershipTest.cpp [hunk 8]
```diff
@@ -0,0 +1,146 @@
...
+ */
+
+#include "CellOwnershipTest.h"
+
+using CellOwnershipTestingTypes =
+    ::testing::Types<autopas::FullParticleCell<Molecule>, autopas::ReferenceParticleCell<Molecule>>;
+
+TYPED_TEST_CASE_P(CellOwnershipTestTyped);
+
+TEST(CellOwnershipTest, testOwnershipFullParticleCell) {
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply tests/testAutopas/tests/cells/CellOwnershipTest.cpp:26]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: tests/testAutopas/tests/cells/CellOwnershipTest.cpp [hunk 9]
```diff
@@ -0,0 +1,146 @@
+/**
+ * @file CellOwnershipTest.cpp
+ * @author D. Martin
+ * @date 10.09.23
+ */
+
+#include "CellOwnershipTest.h"
+
+using CellOwnershipTestingTypes =
+    ::testing::Types<autopas::FullParticleCell<Molecule>, autopas::ReferenceParticleCell<Molecule>>;
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply tests/testAutopas/tests/cells/CellOwnershipTest.cpp:18]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: tests/testAutopas/tests/cells/CellOwnershipTest.h [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+#include "testingHelpers/commonTypedefs.h"
+
+template <typename T>
+class CellOwnershipTestTyped : public AutoPasTestBase {
+ public:
+  CellOwnershipTestTyped() = default;
+
+  ~CellOwnershipTestTyped() override = default;
+
+ private:
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply tests/testAutopas/tests/cells/CellOwnershipTest.h]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: tests/testAutopas/tests/pairwiseFunctors/CellFunctorTest.h (hunk 1 above)
Comment (dmartin13) [reply tests/testAutopas/tests/pairwiseFunctors/CellFunctorTest.h]: done in [7948303](https://github.com/AutoPas/AutoPas/pull/782/commits/7948303a868d18b1f1d8ec9253a224a434f4ac93)

File: src/autopas/particles/OwnershipState.h
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/particles/OwnershipState.h:1]: Initially I wanted to overload these operators, but overloading just by return type is not allowed. 
I have not found a way to implement a cast operator for an `enum class`. For now I simply created a function `toInt64` that handles the `static_cast`.
I could also do something like an "assignment operator":
```
const inline int64_t &operator<<=(int64_t &a, const OwnershipState b) {
  a = static_cast<int64_t>(b);
  return a;
}
```
If there is actually a possibility to create a cast operator or do overloading, please let me know.

[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/autopas/particles/OwnershipState.h:1]: What's wrong with the operators that you implemented?
I fear to have an actual cast operator you would need to wrap the enum in an actual class like our `Option` classes, but I guess that's overkill.

[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/particles/OwnershipState.h:1]: In principle there is nothing wrong with the operators. It just would have been nice if we could also use the same operator to return an int64_t.

File: tests/testAutopas/tests/cells/CellOwnershipTest.cpp [hunk 11]
```diff
@@ -6,81 +6,102 @@
...
+/**
+ * The CellOwnershipTests are only executed for FullParticleCell, ReferenceParticleCell, SortedCellView and
+ * OctreeLeafNode. Note: For OctreeNodeWrapper (which also inherits from ParticleCell) these tests are not executed,
+ * since it only manages internal nodes that store the particles. Only the OctreeLeafNodes store the particles in an
+ * internal storage.
+ * The ClusterTowers (which also inherits from ParticleCell) internally use a FullParticleCell to store particles.
+ */
+
 using CellOwnershipTestingTypes =
     ::testing::Types<autopas::FullParticleCell<Molecule>, autopas::ReferenceParticleCell<Molecule>>;
```
Comment (FG-TUM) [inline tests/testAutopas/tests/cells/CellOwnershipTest.cpp:18]: This doesn't really fit together. The comment suggests that the tests are executed for `FullParticleCell`, `ReferenceParticleCell`, `SortedCellView` and `OctreeLeafNode`. However, the tuple only contains `FullParticleCell` and `ReferenceParticleCell`.

File: src/autopas/particles/OwnershipState.h
[the remark this answers is not in the document]
Comment (FG-TUM) [reply src/autopas/particles/OwnershipState.h:1]: I think that's not necessary. Since the operators take and return `OwnershipState`s we can already chain them and if anyone wants to do make an operation with a value that is not a valid OwnershipState the should do the explicit cast anyway.

File: tests/testAutopas/tests/cells/CellOwnershipTest.cpp (hunk 11 above)
Comment (dmartin13) [reply tests/testAutopas/tests/cells/CellOwnershipTest.cpp]: Okay, I adjusted the tests a bit. A general comment explains why the tests are not executed for ClusterTower and OctreeNodeWrapper. 
The Typed Test is integrated into all other tests (including SortedCellView and OctreeLeafNode) because it makes little sense to have this test for only two different types of cells.

**Comment by FG-TUM** [comment]
please address the merge conflicts first ;)

**Comment by dmartin13** [comment]
> please address the merge conflicts first ;)

done in [c7185db](https://github.com/AutoPas/AutoPas/pull/782/commits/c7185dbc095128dd3c5d4209bb65a09caf2db386)

File: src/autopas/cells/FullParticleCell.h [hunk 12]
```diff
@@ -50,6 +50,17 @@ class FullParticleCell : public ParticleCell<Particle> {
 
   void addParticle(const Particle &p) override {
     std::lock_guard<AutoPasLock> guard(this->_cellLock);
+
+    // sanity check that ensures that only particles of the cells OwnershipState can be added. Note: is a cell is a
```
Comment (SamNewcome) [inline src/autopas/cells/FullParticleCell.h:54]:
```suggestion
    // sanity check that ensures that only particles of the cells OwnershipState can be added. Note: if a cell is a
```

File: src/autopas/cells/ParticleCell.h [hunk 13]
```diff
@@ -82,10 +84,22 @@ class ParticleCell {
...
-   * @return number of particles stored in this cell
+   * Get the number of all particles stored in this cell (owned, halo and dummy).
+   * @return number of particles stored in this cell (owned, halo and dummy).
    */
-  [[nodiscard]] virtual unsigned long numParticles() const = 0;
+  [[nodiscard]] virtual unsigned long size() const = 0;
+
+  /**
+   * Get the number of particles with respect to the specified IteratorBehavior.
+   * Note: Since this function counts the number of the respective particles in the internal particle storage, this is
```
Comment (SamNewcome) [inline src/autopas/cells/ParticleCell.h:94]:
```suggestion
   * @warning Since this function counts the number of the respective particles in the internal particle storage, this is
```

File: src/autopas/containers/ParticleContainerInterface.h [hunk 14]
```diff
@@ -172,10 +172,22 @@ class ParticleContainerInterface {
   virtual void deleteAllParticles() = 0;
 
   /**
-   * Get the total number of particles saved in the container (owned and halo but not dummies).
-   * @return Number of particles in the container.
+   * Get the number of particles with respect to the specified IteratorBehavior.
+   * Note: Since this function counts the number of the respective particles in the internal particle storage, this is
```
Comment (SamNewcome) [inline src/autopas/containers/ParticleContainerInterface.h:176]:
```suggestion
   * @warning Since this function counts the number of the respective particles in the internal particle storage, this is
```

File: src/autopas/containers/octree/OctreeLeafNode.h [hunk 15]
```diff
@@ -79,7 +79,18 @@ class OctreeLeafNode : public OctreeNodeInterface<Particle>, public FullParticle
     }
 
     if ((this->_particles.size() < this->_treeSplitThreshold) or anyNewDimSmallerThanMinSize) {
+      // sanity check that ensures that only particles of the cells OwnershipState can be added. Note: is a cell is a
```
Comment (SamNewcome) [inline src/autopas/containers/octree/OctreeLeafNode.h:82]:
```suggestion
      // sanity check that ensures that only particles of the cells OwnershipState can be added. Note: if a cell is a
```

File: src/autopas/containers/verletClusterLists/ClusterTower.h [hunk 16]
```diff
@@ -187,22 +187,37 @@ class ClusterTower : public ParticleCell<Particle> {
...
+    return _particlesStorage.getNumberOfParticles(behavior);
+  }
 
   /**
-   * Returns the size of the internal particle storage aka. the total number of particles incl. dummies.
-   * @return
+   * Get the number of all particles saved in the tower without dummies for data structure reasons (owned + halo +
+   * dummies for non-datastructure purposes).
+   * @return Number of all particles saved in the tower without dummies for data structure reasons (owned + halo +
+   * dummies for non-datastructure purposes).
```
Comment (SamNewcome) [inline src/autopas/containers/verletClusterLists/ClusterTower.h:206]: Am I correct that the "dummies for data structure reasons" are the tailing dummies to ensure that every cluster is filled? If so, clarify that the number of particles excludes tailing dummies.

**Review by SamNewcome — CHANGES_REQUESTED** [review]

File: src/autopas/cells/FullParticleCell.h (hunk 12 above)
Comment (dmartin13) [reply src/autopas/cells/FullParticleCell.h]: done in[37e2621](https://github.com/AutoPas/AutoPas/pull/782/commits/37e26218410380f7bc586d66bd83b316d23a3d28)

File: src/autopas/cells/ParticleCell.h (hunk 13 above)
Comment (dmartin13) [reply src/autopas/cells/ParticleCell.h]: done in[37e2621](https://github.com/AutoPas/AutoPas/pull/782/commits/37e26218410380f7bc586d66bd83b316d23a3d28)

File: src/autopas/containers/ParticleContainerInterface.h (hunk 14 above)
Comment (dmartin13) [reply src/autopas/containers/ParticleContainerInterface.h]: done in [37e2621](https://github.com/AutoPas/AutoPas/pull/782/commits/37e26218410380f7bc586d66bd83b316d23a3d28)

File: src/autopas/containers/octree/OctreeLeafNode.h (hunk 15 above)
Comment (dmartin13) [reply src/autopas/containers/octree/OctreeLeafNode.h]: done in [37e2621](https://github.com/AutoPas/AutoPas/pull/782/commits/37e26218410380f7bc586d66bd83b316d23a3d28)

File: src/autopas/containers/verletClusterLists/ClusterTower.h (hunk 16 above)
Comment (dmartin13) [reply src/autopas/containers/verletClusterLists/ClusterTower.h]: Yes, these are the tailing dummies. 
Done in [37e2621](https://github.com/AutoPas/AutoPas/pull/782/commits/37e26218410380f7bc586d66bd83b316d23a3d28)

**Review by SamNewcome — APPROVED** [review]

File: src/autopas/cells/ParticleCell.h [hunk 17]
```diff
@@ -128,9 +142,50 @@ class ParticleCell {
...
   /**
-   * Lock object for exclusive access to this cell.
+   * Get the type of particles contained in this cell. Possible values:
+   * dummy: this cell is empty
+   * owned: this cell can ONLY contain owned particles
+   * halo: this cell can ONLY contain halo particles
+   * ownedOrHalo: this cell can contain owned or halo particles
+   * @return type of particles inside this cell
+   */
+  const OwnershipState getPossibleParticleOwnerships() { return _ownershipState; }
```
Comment (FG-TUM) [inline src/autopas/cells/ParticleCell.h:152]:
```suggestion
  OwnershipState getPossibleParticleOwnerships() const { return _ownershipState; }
```
Copied `const` return values have no effect. However, The function itself should be `const`.

File: src/autopas/cells/ParticleCell.h [hunk 18]
```diff
@@ -128,9 +142,50 @@ class ParticleCell {
...
+    _ownershipStateDefined = true;
+  }
+
+  /**
+   * Lock object for exclusive access to this cell. This lock has to be mutable since it is set in
+   * getNumberOfParticles() const.
+   */
+  mutable AutoPasLock _cellLock{};
+
+ protected:
```
Comment (FG-TUM) [inline src/autopas/cells/ParticleCell.h:180]:
```suggestion
 protected:
  /**
   * Lock the object for exclusive access to this cell. This lock has to be mutable since it is set in
   * getNumberOfParticles() const.
   */
  mutable AutoPasLock _cellLock{};
```
Why was this made public?

File: src/autopas/cells/ReferenceParticleCell.h [hunk 19]
```diff
@@ -235,7 +263,7 @@ class ReferenceParticleCell : public ParticleCell<Particle> {
   SoA<SoAArraysType> _particleSoABuffer;
 
  private:
-  AutoPasLock _particlesLock;
+  mutable AutoPasLock _particlesLock;
```
Comment (FG-TUM) [inline src/autopas/cells/ReferenceParticleCell.h:266]: why do we even have this lock? Shouldn't we use `_cellLock` from the parent class?

File: src/autopas/containers/ParticleContainerInterface.h [hunk 20]
```diff
@@ -172,10 +172,22 @@ class ParticleContainerInterface {
...
-   * @return Number of particles in the container.
+   * Get the number of particles with respect to the specified IteratorBehavior.
+   * @warning: Since this function counts the number of the respective particles in the internal particle storage, this
+   * is in O(n) + lock is required. Only use it when it is absolutely necessary to have the exact number of different
+   * particle types like owned or halo. If it is enough to have the whole number of particles (owned + halo + dummy),
+   * the function size() can be used.
+   * @param behavior Behavior of the iterator, see IteratorBehavior.
+   * @return The number of particles with respect to the specified IteratorBehavior.
+   */
+  [[nodiscard]] virtual unsigned long getNumberOfParticles(
```
Comment (FG-TUM) [inline src/autopas/containers/ParticleContainerInterface.h:183]:
```suggestion
  [[nodiscard]] virtual size_t getNumberOfParticles(
```

File: src/autopas/pairwiseFunctors/CellFunctor.h [hunk 21]
```diff
@@ -132,9 +138,19 @@ template <class Particle, class ParticleCell, class ParticleFunctor, DataLayoutO
 void CellFunctor<Particle, ParticleCell, ParticleFunctor, DataLayout, useNewton3, bidirectional>::processCellPair(
 
     ParticleCell &cell1, ParticleCell &cell2, const std::array<double, 3> &sortingDirection) {
-  if ((DataLayout == DataLayoutOption::soa && (cell1._particleSoABuffer.getNumberOfParticles() == 0 ||
-                                               cell2._particleSoABuffer.getNumberOfParticles() == 0)) ||
-      (DataLayout == DataLayoutOption::aos && (cell1.numParticles() == 0 || cell2.numParticles() == 0))) {
+  if ((DataLayout == DataLayoutOption::soa &&
+       (cell1._particleSoABuffer.size() == 0 and cell2._particleSoABuffer.size() == 0)) or
+      (DataLayout == DataLayoutOption::aos && (cell1.size() == 0 and cell2.size() == 0))) {
+    return;
```
Comment (FG-TUM) [inline src/autopas/pairwiseFunctors/CellFunctor.h:144]:
```suggestion
  if ((DataLayout == DataLayoutOption::soa and
       (cell1._particleSoABuffer.size() == 0 and cell2._particleSoABuffer.size() == 0)) or
      (DataLayout == DataLayoutOption::aos and (cell1.size() == 0 and cell2.size() == 0))) {
    return;
```

**Review by FG-TUM — CHANGES_REQUESTED** [review]

**Review by thesamriel — APPROVED** [review]

File: src/autopas/cells/ParticleCell.h (hunk 17 above)
Comment (dmartin13) [reply src/autopas/cells/ParticleCell.h]: done in [06385c2](https://github.com/AutoPas/AutoPas/pull/782/commits/06385c264cc416ebc407bb395db2e8d1a70c1cd0)

File: src/autopas/cells/ParticleCell.h (hunk 18 above)
Comment (dmartin13) [reply src/autopas/cells/ParticleCell.h:179]: As far as I can see, this lock is only used from outside in `checkParticleInCellAndUpdateByIDAandPosition()` from `ParticleCellHelpers.h`. But I could write a getter for this lock, then we can move it to protected section?

File: src/autopas/cells/ReferenceParticleCell.h (hunk 19 above)
Comment (dmartin13) [reply src/autopas/cells/ReferenceParticleCell.h]: Good point, I came across this as well while writing the new functions and wanted to ask you if there was any reason why this extra lock was used. But then I forgot to ask.
Seems also to work with the lock from parent... So done in [06385c2](https://github.com/AutoPas/AutoPas/pull/782/commits/06385c264cc416ebc407bb395db2e8d1a70c1cd0)

File: src/autopas/containers/ParticleContainerInterface.h (hunk 20 above)
Comment (dmartin13) [reply src/autopas/containers/ParticleContainerInterface.h]: done in [06385c2](https://github.com/AutoPas/AutoPas/pull/782/commits/06385c264cc416ebc407bb395db2e8d1a70c1cd0)
Should we also do this for `size()` ?

File: src/autopas/pairwiseFunctors/CellFunctor.h (hunk 21 above)
Comment (dmartin13) [reply src/autopas/pairwiseFunctors/CellFunctor.h]: done in [06385c2](https://github.com/AutoPas/AutoPas/pull/782/commits/06385c264cc416ebc407bb395db2e8d1a70c1cd0)

File: src/autopas/containers/verletClusterLists/ClusterTower.h [hunk 22]
```diff
@@ -187,22 +187,37 @@ class ClusterTower : public ParticleCell<Particle> {
...
    */
-  [[nodiscard]] size_t getNumAllParticles() const { return _particlesStorage.numParticles(); }
+  [[nodiscard]] unsigned long getNumActualParticles() const {
+    return _particlesStorage.size() - getNumTailDummyParticles();
+  }
+
+  /**
+   * @copydoc autopas::ParticleCell::getPossibleParticleOwnerships()
+   */
+  const OwnershipState getPossibleParticleOwnerships() { return _particlesStorage.getPossibleParticleOwnerships(); }
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/containers/verletClusterLists/ClusterTower.h:215]: done in [06385c2](https://github.com/AutoPas/AutoPas/pull/782/commits/06385c264cc416ebc407bb395db2e8d1a70c1cd0)

File: src/autopas/containers/verletClusterLists/VerletClusterLists.h [hunk 23]
```diff
@@ -772,14 +772,37 @@ class VerletClusterLists : public ParticleContainerInterface<Particle>, public i
...
+  /**
+   * @copydoc autopas::ParticleContainerInterface::getNumberOfParticles()
+   */
+  [[nodiscard]] unsigned long getNumberOfParticles(IteratorBehavior behavior) const override {
+    // sum up all particles in towers that fulfill behavior
+    size_t sum = std::accumulate(_towers.begin(), _towers.end(), 0, [&behavior](size_t acc, const auto &tower) {
+      return acc + tower.getNumberOfParticles(behavior);
+    });
+
+    // sum up all particles in that are inserted into towers in the next rebuild
```
[the remark this answers is not in the document]
Comment (dmartin13) [reply src/autopas/containers/verletClusterLists/VerletClusterLists.h]: I tried to make this a little bit more clear in [06385c2](https://github.com/AutoPas/AutoPas/pull/782/commits/06385c264cc416ebc407bb395db2e8d1a70c1cd0)

File: src/autopas/containers/ParticleContainerInterface.h (hunk 20 above)
Comment (FG-TUM) [reply src/autopas/containers/ParticleContainerInterface.h]: technically it doesn't matter but for consistency yes please

File: src/autopas/cells/ParticleCell.h (hunk 18 above)
Comment (FG-TUM) [reply src/autopas/cells/ParticleCell.h:179]: yes a getter is fine, just no setter ;)

File: src/autopas/containers/ParticleContainerInterface.h (hunk 20 above)
Comment (dmartin13) [reply src/autopas/containers/ParticleContainerInterface.h]: done in [94c85bf](https://github.com/AutoPas/AutoPas/pull/782/commits/94c85bf7a061dbad59c9a4e2f931bbd52c27b653)

File: src/autopas/cells/ParticleCell.h (hunk 18 above)
Comment (dmartin13) [reply src/autopas/cells/ParticleCell.h]: done in [94c85bf](https://github.com/AutoPas/AutoPas/pull/782/commits/94c85bf7a061dbad59c9a4e2f931bbd52c27b653)

**Review by FG-TUM — APPROVED** [review]
