### PR TITLE
Tuning Strategy Config Wipe Fix

### LINKED ISSUE #894: Tuning Strats can't abort tuning phase
**Describe the bug**
Some tuning strategies, like Random or Bayesian strategies, want to terminate tuning after a given number of samples has been collected. They do this by flushing the config queue.

This collides with our mechanism that checks that strategies do not accidentally wipe the queue.
If such a wipe is detected, any changes by the wiping strategy are reverted.

**To Reproduce**
Run:
```bash
md-flexible \
  --tuning-strategies random-Search \
  --tuning-max-evidence 2 \
  --tuning-samples 2 \
  --iterations 20 \
  --no-flops \
  --no-end-config
```

**Expected behavior**
The scenario above should only do four tuning iterations but instead does 20.

**Additional context**
The wipe checker was introduced in #858

### PR DESCRIPTION
**Pull request by dmartin13**
# Description
As described in #894, some tuning strategies, like Random or Bayesian strategies, want to terminate tuning after a given number of samples has been collected. They do this by flushing the config queue.

Until now, however, this flushing was reset by the config wipe checker.

An optional flag (`intentionalConfigWipe`) has been introduced to indicate that the config wipe was intentional and the config wipe checker does not reset the queue. 

## Resolved Issues

- [x] fixes #894 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
The scenario in #894 was used to test the behavior. Instead of the 20/20 tuning iterations it does now 4/20 tuning iterations.
```
md-flexible \
  --tuning-strategies random-Search \
  --tuning-max-evidence 2 \
  --tuning-samples 2 \
  --iterations 20 \
  --no-flops \
  --no-end-config
```

### CODE REVIEW

File: src/autopas/tuning/AutoTuner.cpp [hunk 1]
```diff
@@ -95,11 +95,11 @@ bool AutoTuner::tuneConfiguration() {
...
       _configQueue = configQueueBackup;
+      AutoPasLog(WARN, "ConfigQueue wipe by {} detected! Resetting to previous state: (Size={}) {}",
+                 stratOpt.to_string(), _configQueue.size(),
+                 utils::ArrayUtils::to_string(_configQueue, ", ", {"[", "]"},
+                                              [](const auto &conf) { return conf.toShortString(false); }));
     }
-    AutoPasLog(WARN, "ConfigQueue wipe by {} detected! Resetting to previous state: (Size={}) {}", stratOpt.to_string(),
-               _configQueue.size(), utils::ArrayUtils::to_string(_configQueue, ", ", {"[", "]"}, [](const auto &conf) {
-                 return conf.toShortString(false);
-               }));
```
Comment (dmartin13) [inline src/autopas/tuning/AutoTuner.cpp:102]: I noticed that regardless of whether the queue is empty or not, the warning `AutoPasLog(WARN, “ConfigQueue...` is issued. Is that correct? I have now changed this so that the warning is only printed if the `_configQueue` is empty.

File: src/autopas/tuning/tuningStrategy/RandomSearch.cpp [hunk 2]
```diff
@@ -15,21 +15,27 @@ autopas::RandomSearch::RandomSearch(size_t maxEvidence, unsigned long seed)
...
+    if (intentionalConfigWipe) {
+      intentionalConfigWipe->get() = true;
+    }
   } else {
     // Swap a randomly selected configuration to the end.
     std::uniform_int_distribution<std::mt19937::result_type> distribution(0, configQueue.size() - 1);
     const auto selectedIndex = distribution(_rng);
     std::swap(configQueue.back(), configQueue[selectedIndex]);
+    ++_numEvidenceCollected;
   }
```
Comment (dmartin13) [inline src/autopas/tuning/tuningStrategy/RandomSearch.cpp:33]: I noticed that `_numEvidenceCollected` is never incremented. Accordingly, you never get into the case that `_numEvidenceCollected == _maxEvidence` and the config is wiped. I have now changed this and `_numEvidenceCollected` is incremented. Hope this is correct.

File: src/autopas/tuning/AutoTuner.cpp (hunk 1 above)
Comment (FG-TUM) [reply src/autopas/tuning/AutoTuner.cpp:102]: Classic off by 1 error. The closing bracket was one line too early ;)
Good you found that. Yesterday I was annoyed about this message being so spammy so I put it on my debug todo list for next week.

File: src/autopas/tuning/tuningStrategy/TuningStrategyInterface.h [hunk 3]
```diff
@@ -50,9 +53,12 @@ class TuningStrategyInterface {
...
    * @param configQueue Queue of configurations to be tested. The tuning strategy should edit this queue.
    * @param evidenceCollection All collected evidence until now.
+   * @param intentionalConfigWipe Optional flag that is used by tuning strategies to signal they have intentionally
+   * wiped the config queue
    */
-  virtual void optimizeSuggestions(std::vector<Configuration> &configQueue,
-                                   const EvidenceCollection &evidenceCollection) = 0;
+  virtual void optimizeSuggestions(
+      std::vector<Configuration> &configQueue, const EvidenceCollection &evidenceCollection,
+      std::optional<std::reference_wrapper<bool>> intentionalConfigWipe = std::nullopt) = 0;
```
Comment (FG-TUM) [inline src/autopas/tuning/tuningStrategy/TuningStrategyInterface.h:61]: Why is the parameter a `std::optional` that holds a reference? Why not a reference to a `std::optional`? That would also save us a copy. Or does this not work with the default parameter?

I'm not a huge fan of in/out parameters like these in general as well as default parameters on virtual methods :/ Why not simply return the object or just true / false?

File: src/autopas/tuning/tuningStrategy/RandomSearch.cpp (hunk 2 above)
Comment (FG-TUM) [reply src/autopas/tuning/tuningStrategy/RandomSearch.cpp:33]: Good catch that is indeed a mistake!

The increment should, however, happen in `addEvidence()` for which there is no override yet so please add that and move it there.

**Review by FG-TUM — CHANGES_REQUESTED** [review]

**Comment by FG-TUM** [comment]
> The scenario in https://github.com/AutoPas/AutoPas/issues/894 was used to test the behavior. Instead of the 20/20 tuning iterations it does now 6/20 tuning iterations.

I hope you mean 4/20 instead of 6/20? :D

**Comment by dmartin13** [comment]
> > The scenario in #894 was used to test the behavior. Instead of the 20/20 tuning iterations it does now 6/20 tuning iterations.
> 
> I hope you mean 4/20 instead of 6/20? :D

Yes this was a mistake!
```
Total number of particles at the end of Simulation: 5832
Owned: 1000
Halo : 4832
Measurements:
Total accumulated                  : 159546247 ns (0.160s)
  Initialization                   :   9191840 ns (0.009s) =  5.761%
  Simulate                         : 150353081 ns (0.150s) = 94.238%
    PositionUpdate                 :    569306 ns (0.001s) =  0.379%
    UpdateContainer                :   3393096 ns (0.003s) =  2.257%
    Boundaries                     :  27964334 ns (0.028s) = 18.599%
      HaloParticleExchange         :  27147683 ns (0.027s) = 97.058%
      ReflectParticlesAtBoundaries :      6287 ns (0.000s) =  0.022%
      MigratingParticleExchange    :    816651 ns (0.001s) =  2.920%
    ForceUpdateTotal               : 116223712 ns (0.116s) = 77.301%
      Tuning                       :  67566359 ns (0.068s) = 58.135%
      ForceUpdateTuning            :  67566359 ns (0.068s) = 58.135%
      ForceUpdateNonTuning         :  48653922 ns (0.049s) = 41.862%
    VelocityUpdate                 :    347192 ns (0.000s) =  0.231%
    LoadBalancing                  :     10160 ns (0.000s) =  0.007%
One iteration                      :   7517654 ns (0.008s) =  4.712%
Total wall-clock time              : 159546247 ns (0.160s) =100.000%

Tuning iterations                  : 4 / 20 = 20%
MFUPs/sec                          : 0.172082
```

File: src/autopas/tuning/tuningStrategy/RandomSearch.cpp (hunk 2 above)
Comment (dmartin13) [reply src/autopas/tuning/tuningStrategy/RandomSearch.cpp]: done in [976b882](https://github.com/AutoPas/AutoPas/pull/936/commits/976b88217759053e644121139c2901b725f69ffc)

File: src/autopas/tuning/tuningStrategy/TuningStrategyInterface.h (hunk 3 above)
Comment (dmartin13) [reply src/autopas/tuning/tuningStrategy/TuningStrategyInterface.h]: Changed this out-parameter to a bool return type in [976b882](https://github.com/AutoPas/AutoPas/pull/936/commits/976b88217759053e644121139c2901b725f69ffc)

**Review by FG-TUM — APPROVED** [review]
