### PR TITLE
Fix calculation of DirectSum (wrong sorting) and VerletListsCells (interactions with halo particle were skipped)

### LINKED ISSUE #352: DirectSum produces wrong results in ls1-mardyn
**Describe the bug**
Using the DirectSum traversal I get wrong results using ls1-mardyn:

**To Reproduce**
1. Use current adaptions for the iterator changes of ls1 branch: feature/autopas-2019-09-17
2. run ./src/MarDyn ../examples/Argon/200K_18mol_l/config_autopas_aos.xml --steps=20
3. results jump around:
```
INFO:   20190917T092249 0.215618 [0]    Simstep = 0     T = 2.53016e-05 U_pot = -1.81573        p = -1.03462e-07
[2019-09-17 09:22:49.885] [AutoPasLog] [debug] Skipping container update.
INFO:   20190917T092249 0.216565 [0]    DDBase: Populating halo.
[2019-09-17 09:22:51.774] [AutoPasLog] [debug] Iterating with configuration: {Container: DirectSum , CellSizeFactor: 1.000000 , Traversal: directSum , Data Layout: Array-of-Structures , Newton 3: enabled}
[2019-09-17 09:22:51.774] [AutoPasLog] [debug] Using traversal directSum.
[2019-09-17 09:22:51.940] [AutoPasLog] [debug] IteratePairwise took 165888378 nanoseconds
INFO:   20190917T092251 2.27592  [0]    Simstep = 1     T = 2.53747e-05 U_pot = -1.81596        p = -1.04213e-07
[2019-09-17 09:22:51.945] [AutoPasLog] [debug] Skipping container update.
INFO:   20190917T092251 2.27682  [0]    DDBase: Populating halo.
[2019-09-17 09:22:53.823] [AutoPasLog] [debug] Iterating with configuration: {Container: DirectSum , CellSizeFactor: 1.000000 , Traversal: directSum , Data Layout: Array-of-Structures , Newton 3: enabled}
[2019-09-17 09:22:53.823] [AutoPasLog] [debug] Using traversal directSum.
[2019-09-17 09:22:53.988] [AutoPasLog] [debug] IteratePairwise took 165360417 nanoseconds
[2019-09-17 09:22:53.988] [AutoPasLog] [debug] Collected times for
{Container: DirectSum , CellSizeFactor: 1.000000 , Traversal: directSum , Data Layout: Array-of-Structures , Newton 3: enabled} : [ 165572530 165888378 165360417 ] Reduced value: 165572530
INFO:   20190917T092253 4.32422  [0]    Simstep = 2     T = 0.000333389 U_pot = -1.81772        p = 3.83546e-07
[2019-09-17 09:22:53.993] [AutoPasLog] [debug] Initiating container update.
INFO:   20190917T092253 4.32568  [0]    DDBase: Adding + shifting invalid particles.
INFO:   20190917T092253 4.3257   [0]    DDBase: Populating halo.
[2019-09-17 09:22:54.018] [AutoPasLog] [debug] CellsPerDimensionWithHalo[0]=5
[2019-09-17 09:22:54.018] [AutoPasLog] [debug] CellsPerDimensionWithHalo[1]=5
[2019-09-17 09:22:54.018] [AutoPasLog] [debug] CellsPerDimensionWithHalo[2]=5
[2019-09-17 09:22:54.088] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
[2019-09-17 09:22:54.088] [AutoPasLog] [debug] Using traversal c08.
[2019-09-17 09:22:54.646] [AutoPasLog] [debug] IteratePairwise took 557426257 nanoseconds
INFO:   20190917T092254 4.9819   [0]    Simstep = 3     T = 0.000557864 U_pot = -2.10336        p = 5.70767e-07
[2019-09-17 09:22:54.651] [AutoPasLog] [debug] Skipping container update.
INFO:   20190917T092254 4.98287  [0]    DDBase: Populating halo.
[2019-09-17 09:22:54.690] [AutoPasLog] [debug] Iterating with configuration: {Container: LinkedCells , CellSizeFactor: 1.000000 , Traversal: c08 , Data Layout: Array-of-Structures , Newton 3: enabled}
[2019-09-17 09:22:54.690] [AutoPasLog] [debug] Using traversal c08.
[2019-09-17 09:22:55.245] [AutoPasLog] [debug] IteratePairwise took 554623343 nanoseconds
INFO:   20190917T092255 5.58088  [0]    Simstep = 4     T = 0.000618318 U_pot = -2.10591        p = 6.57583e-07
[2019-09-17 09:22:55.250] [AutoPasLog] [debug] Skipping container update.
INFO:   20190917T092255 5.58185  [0]    DDBase: Populating halo.
```

**Expected behavior**
DirectSum should produce proper results.

### LINKED ISSUE #355: HaloCalculationTest fails for Verlet lists cells with enabled newton3
**Describe the bug**
The new Test fails for the C04SoaTraversal if the cell size factor is 0.5:
```
        502 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_sliced_Array_of_Structures_N3enabled_cellSizeFactor0_500000#GetParam()=((3,5),0,1,0.5) (Failed)
        503 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_sliced_Array_of_Structures_N3enabled_cellSizeFactor1_000000#GetParam()=((3,5),0,1,1) (Failed)
        504 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_sliced_Array_of_Structures_N3enabled_cellSizeFactor1_500000#GetParam()=((3,5),0,1,1.5) (Failed)
        514 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_c18_Array_of_Structures_N3enabled_cellSizeFactor0_500000#GetParam()=((3,6),0,1,0.5) (Failed)
        515 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_c18_Array_of_Structures_N3enabled_cellSizeFactor1_000000#GetParam()=((3,6),0,1,1) (Failed)
        516 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_c18_Array_of_Structures_N3enabled_cellSizeFactor1_500000#GetParam()=((3,6),0,1,1.5) (Failed)
```

**To Reproduce**
1. Run new test from #353 

**Expected behavior**
Does not fail

### PR DESCRIPTION
**Pull request by SteffenSeckler**
# Description

- Fixes inappropriate sorting directions being used in some cases. (mainly DirectSum, but possibly also verlet lists)
- Fixes VerletListsCellsTraversal not iterating over verlet lists of some halo cells (#355)

## Resolved Issues

- [x] fixes #352 
- [x] fixes #355 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Using ls1 mardyn
- [x] Additional Test for AutoPas that includes checking of halos

### CODE REVIEW

**Comment by SteffenSeckler** [comment]
The new tests fail for:
```
        481 - Generated/AutoPasInterfaceTest.HaloCalculationTest/LinkedCells_c04SoA_Structure_of_Arrays_N3disabled_cellSizeFactor0_500000#GetParam()=((1,15),1,0,0.5) (Failed)
        484 - Generated/AutoPasInterfaceTest.HaloCalculationTest/LinkedCells_c04SoA_Structure_of_Arrays_N3enabled_cellSizeFactor0_500000#GetParam()=((1,15),1,1,0.5) (Failed)
        502 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_sliced_Array_of_Structures_N3enabled_cellSizeFactor0_500000#GetParam()=((3,5),0,1,0.5) (Failed)
        503 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_sliced_Array_of_Structures_N3enabled_cellSizeFactor1_000000#GetParam()=((3,5),0,1,1) (Failed)
        504 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_sliced_Array_of_Structures_N3enabled_cellSizeFactor1_500000#GetParam()=((3,5),0,1,1.5) (Failed)
        514 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_c18_Array_of_Structures_N3enabled_cellSizeFactor0_500000#GetParam()=((3,6),0,1,0.5) (Failed)
        515 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_c18_Array_of_Structures_N3enabled_cellSizeFactor1_000000#GetParam()=((3,6),0,1,1) (Failed)
        516 - Generated/AutoPasInterfaceTest.HaloCalculationTest/VerletListsCells_verlet_c18_Array_of_Structures_N3enabled_cellSizeFactor1_500000#GetParam()=((3,6),0,1,1.5) (Failed)

```

**Comment by SteffenSeckler** [comment]
verlet lists cells is already fixed in this. However, #354 is still an issue, which will not be fixed in this PR (because of missing knowledge)

File: src/autopas/containers/cellPairTraversals/C18BasedTraversal.h [hunk 1]
```diff
@@ -41,19 +41,24 @@ class C18BasedTraversal : public CBasedTraversal<ParticleCell, PairwiseFunctor,
   /**
    * The main traversal of the C18Traversal.
    * @copydetails C01BasedTraversal::c01Traversal()
+   * @tparam allCells Defines whether or not to iterate over all cells with the loop body given as argument. By default
+   * it will not iterate over all cells and instead skip the last few cells, because they will be covered by the base
```
Comment (FG-TUM) [inline src/autopas/containers/cellPairTraversals/C18BasedTraversal.h]: From this description it is not directly clear to me:
1) how much is "last few cells" (suppose last row * overlap?)
2) when would I set this to true / false
maybe then also rename it accordingly?

File: src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h [hunk 2]
```diff
@@ -110,10 +110,13 @@ class SlicedBasedTraversal : public CellPairTraversal<ParticleCell> {
...
   /**
-   * The main traversal of the C01Traversal.
+   * The main traversal of the sliced traversal.
    * @copydetails C01BasedTraversal::c01Traversal()
+   * @tparam allCells Defines whether or not to iterate over all cells with the loop body given as argument. By default
+   * it will not iterate over all cells and instead skip the last few cells, because they will be covered by the base
+   * step.
    */
-  template <typename LoopBody>
+  template <bool allCells = false, typename LoopBody>
```
Comment (FG-TUM) [inline src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h]: see above

File: src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h [hunk 3]
```diff
@@ -139,10 +138,10 @@ class C04SoACellHandler {
    * @param bufferSlice Index of slice in combinationSlice (source)
    * @param cellSlice Index of slice in _baseOffsets (destination)
    */
-  void writeBufferIntoCell(std::vector<ParticleCell> &cells, const unsigned long baseIndex,
+  void writeBufferIntoCell(std::vector<ParticleCell> &cells, unsigned long baseIndex,
```
Comment (FG-TUM) [inline src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h]: why remove const?

File: src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h [hunk 4]
```diff
@@ -350,17 +349,18 @@ inline void C04SoACellHandler<ParticleCell, PairwiseFunctor, DataLayout, useNewt
       }
     }
   }
+  int id = 0;
   for (unsigned long x = 0ul; x <= _overlap[0]; ++x) {
     for (unsigned long y = 0ul; y <= _overlap[1]; ++y) {
-      for (unsigned long z = 0ul; z <= _overlap[2]; ++z) {
+      for (unsigned long z = 0ul; z <= _overlap[2]; ++z, ++id) {
```
Comment (FG-TUM) [inline src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h]:
```suggestion
      for (unsigned long z = 0ul; z <= _overlap[2]; ++z) {
```
this was just for debugging

File: src/autopas/pairwiseFunctors/CellFunctor.h [hunk 5]
```diff
@@ -42,19 +42,19 @@ class CellFunctor {
...
    */
   void processCell(ParticleCell &cell);
 
   /**
    * Process the interactions between the particles of cell1 with particles of cell2.
    * @param cell1
    * @param cell2
-   * @param r Normalized vector connecting centers of cell1 and cell2. If no parameter is given, a default value is used
-   * which is always applicable.
+   * @param sortingDirection Normalized vector connecting centers of cell1 and cell2. If no parameter is given, sorting
```
Comment (FG-TUM) [inline src/autopas/pairwiseFunctors/CellFunctor.h]:
```suggestion
   * @param sortingDirection Normalized vector connecting centers of cell1 and cell2. If no parameter or {0, 0, 0} is given, sorting
```

File: tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp [hunk 6]
```diff
@@ -212,22 +212,23 @@ void doSimulationLoop(autopas::AutoPas<Molecule, FMCell> &autoPas1, autopas::Aut
...
   }
-  ASSERT_EQ(numParticles, 2) << "The container should own exactly two particles!";
+  ASSERT_EQ(numParticles, numParticlesExpected)
+      << "The container should own exactly " << numParticlesExpected << " particles!";
 
   for (auto &mol : molecules) {
-    EXPECT_DOUBLE_EQ(autopas::ArrayMath::dot(mol.getF(), mol.getF()), 390144. * 390144)
-        << "wrong force calculated.";  // this value should be correct already
+    EXPECT_NEAR(autopas::ArrayMath::dot(mol.getF(), mol.getF()), 390144. * 390144., 1.)
+        << "wrong force calculated for particle: " << mol.toString();  // this value should be correct already
```
Comment (FG-TUM) [inline tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp]: This comment is not really helping^^

File: tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp [hunk 7]
```diff
@@ -316,7 +321,61 @@ void testSimulationLoop(testingTuple options) {
...
 
-  doAssertions(autoPas, &functor);
+  doAssertions(autoPas, &functor, 2);
+}
+
+/**
+ * This test checks the correct calculation of an AutoPas container, where:
+ * The container owns 26 particles, that lie with a distance of 0.25 away from the centers of the faces and edges, as
+ * well as from the corners of the box. They always lie on a straight line `a` from these points to the center of the
+ * box. In addition the container owns 26 halo particles that lie outside of the container on the same line `a` with a
```
Comment (FG-TUM) [inline tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp]:
```suggestion
 * box. Additionally, the container owns 26 halo particles that lie outside of the container on the same line `a` with a
```

File: tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp [hunk 8]
```diff
@@ -335,6 +394,22 @@ TEST_P(AutoPasInterfaceTest, SimulatonLoopTest) {
   }
 }
 
+TEST_P(AutoPasInterfaceTest, HaloCalculationTest) {
+  // this test checks the correct behavior of the autopas interface.
```
Comment (FG-TUM) [inline tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp]: 1) move this comment above the test head.
2) with respect to what?

File: src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h (hunk 3 above)
Comment (SteffenSeckler) [reply src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h]: because it doesn't have any effect here.
(const for copy by value has only an effect in function implementation, not the declaration)

File: src/autopas/containers/cellPairTraversals/C18BasedTraversal.h (hunk 1 above)
Comment (SteffenSeckler) [reply src/autopas/containers/cellPairTraversals/C18BasedTraversal.h]: more explanations added, but no rename done, as the name is descriptive
